### ISSUE TITLE
Proposing to OCA Addons?

### ISSUE THREAD

**Issue by JonathanNEMRY** [Yenthe666/auto_backup#100]
Hi @Yenthe666 

thanks for this great addons.
have you ever thought of proposing it to OCA addons? 

-jne

**Comment by Yenthe666** [comment]
Hi @JonathanNEMRY,

Thanks for the suggestion, OCA actually took it over already! See https://github.com/OCA/server-tools/tree/11.0/auto_backup
I just chose to maintain my version and keep it 'my way' too basically.
