### ISSUE TITLE
can't find Backup scheduler

### ISSUE THREAD

**Issue by Jeffys** [Yenthe666/auto_backup#109]
Hi Yenthe,
I tried to install your module on odoo11 Enterprise but once installed I can't find the 'Backup sheduler' in the Scheduled Actions .
Do you have an idea?
Thanks a lot
Jeff

**Comment by Donderda** [comment]
Were you able to find it? I can't find it in odoo11 Enterprise neither :(

**Comment by Donderda** [comment]
Maybe this helps: When I try to install the module, I get this log messages:

```
web_1  | 2018-12-05 10:01:23,009 16 INFO xxxx odoo.modules.loading: 92 modules loaded in 0.22s, 0 queries
web_1  | 2018-12-05 10:01:23,012 16 DEBUG xxxx odoo.modules.module: module auto_backup: no manifest file found ('__manifest__.py', '__openerp__.py')
web_1  | 2018-12-05 10:01:23,013 16 WARNING xxxx odoo.modules.graph: module auto_backup: not installable, skipped
```

**Comment by Yenthe666** [comment]
@Donderda your Odoo is complaining about not being able to find the manifest file. Are you sure your module has correct access rights and has the manifest file too?

**Comment by Donderda** [comment]
@Yenthe666 Thank you for your reply. I just downloaded the module from [here](https://www.odoo.com/apps/modules/11.0/auto_backup/) and uploaded it via the Apps-App... Did I miss something?

**Comment by Yenthe666** [comment]
Hmm I never tried it that way. Have you ever tried to add it manually in your server under your custom addons path?

**Comment by Donderda** [comment]
Just tried it. Seems to work :). Thank you 👍

**Comment by Yenthe666** [comment]
You're welcome :)
