### ISSUE TITLE
filename format for auto_backup ?

### ISSUE THREAD

**Issue by dfang** [Yenthe666/auto_backup#111]
it seems auto_backup backup files to `date_time_db.zip` and default to UTC time format ?

how to change the other timezone format ?

**Comment by Yenthe666** [comment]
Hi @dfang,

Indeed, it uses the current (server) datetime for the filename.
If you want to modify that you can do it at https://github.com/Yenthe666/auto_backup/blob/763321d2ff7bf84d2bd01539f81d41def80421e3/auto_backup/models/db_backup.py#L156

Regards,
Yenthe
