### ISSUE TITLE
Why do I have to fill in the url?

### ISSUE THREAD

**Issue by Linekio** [Yenthe666/auto_backup#113]
It's not a real issue, but I think it's weird to use XMLRPC since the module can't backup a remote instance of odoo.
I propose:
```
from odoo import service
[...]
    @api.multi
    def get_db_list(self):
        return service.db.list_dbs()
```

**Comment by Yenthe666** [comment]
Hi there,

It is actually a trick to get and check the name of the db to backup. Without this the script wouldn't work.

Regards,
Yenthe
