### ISSUE TITLE
[8.0]About backup exception

### ISSUE THREAD

**Issue by lonelyleaves** [Yenthe666/auto_backup#115]
hello ，i have install this function，and In the backup, encountered an error, what should this problem be, how to solve the need, pg_dump backup down of SQL file size around 1gb, is it because the file is too large？ thank you!

false information：
NameError: global name 'logger' is not defined

**Comment by Yenthe666** [comment]
Hi,

Sorry for the late reply. It looks like the logger bundle was not found/installed on your system. If you remove those lines it'll work.
