### ISSUE TITLE
Date not synchronized

### ISSUE THREAD

**Issue by deejayalbatros** [Yenthe666/auto_backup#116]
The date on my Ubuntu machnine is different from the date in the created zip backup files. 

![2018-11-02 10_43_36-window](https://user-images.githubusercontent.com/16037565/47893015-59042900-de8d-11e8-86e9-2db2a978ba7f.png)

![2018-11-02 10_43_48-window](https://user-images.githubusercontent.com/16037565/47893023-628d9100-de8d-11e8-86fd-8e3c4ceb2b0c.png)

How to match the zips to the machine date??

**Comment by deejayalbatros** [comment]
I can find it can be done with import pytz but will it work in your python file?

I found this example:

import pytz, datetime

timeUTC = datetime.datetime(2013, 5, 23, 19, 27, 50, 0)
timezoneLocal = pytz.timezone('Asia/Jakarta')
utc = pytz.utc
timeLocal = utc.localize(timeUTC).astimezone(timezoneLocal)
print(timeLocal)
# 2013-05-23 22:27:50+03:00

If it's correct I am not sure where to paste this exactly using gedit so any help regarding making this work would be appreciated...

**Comment by deejayalbatros** [comment]
Anyone?

**Comment by Yenthe666** [comment]
@deejayalbatros yes you can change the date formatting and timezones as you like within the module. It just needs some custom coding, which you should really try to figure out yourself 😉 
Remember: don't code if you don't know how to code hehe.

**Comment by deejayalbatros** [comment]
I'm not a coder so that's it then?

**Comment by Yenthe666** [comment]
@deejayalbatros well you could give it a try in a local development machine or something, I wouldn't do it on your production environment though. Dates, timezones and converting can be hard so you might need quite some time to get it done. I'm afraid nobody is going to see this issue (even if I'd keep it open) and would be coding that 'just to help out', sorry to say.
