### ISSUE TITLE
DB backup issue for Size > 5 GB

### ISSUE THREAD

**Issue by JADCO5692** [Yenthe666/auto_backup#117]
Hi,
I am trying to use this module for a DB having a size more than 5 GB but it is not able to backup that.
Please suggest.
Regards,
Himanshu Mittal

**Comment by Yenthe666** [comment]
Hi @JADCO5692,

It is possible that your server itself closes off the SSH session after a specific session.
Have a look at the `ServerAliveInterval` of your server.
