### ISSUE TITLE
Not install In Odoo12.

### ISSUE THREAD

**Issue by asiamatrix** [Yenthe666/auto_backup#120]
I do not install on Odoo 12 with source install.

**Comment by Yenthe666** [comment]
Sorry? I really need more info and details as I don't even get what you're trying to say or ask.

**Comment by asiamatrix** [comment]
See in video
[https://youtu.be/g2c_EQs3ORU](url)

**Comment by Yenthe666** [comment]
Can you try the suggestions in the other thread please (just commented)?

**Comment by Yenthe666** [comment]
I really don't get why it fails for some people. Can you open the file on your server that contains the security rights? (the csv)

**Comment by Yenthe666** [comment]
Yeah sorry but without a reproducable way I can't do much. 
What OS? Enough security rights on all files in the folder? Can you open the file and see the content? Etc, etc.

**Comment by asiamatrix** [comment]
I use Ubuntu 18.4.
Odoo 12 Enterprise Edition.
Install Odoo with Source.
Download your module from https://www.odoo.com/apps/modules/12.0/auto_backup/.

**Comment by Yenthe666** [comment]
Enough security rights on all files in the folder? Can you open the file and see the content?

**Comment by asiamatrix** [comment]
Here is the security folder.
![image](https://user-images.githubusercontent.com/44358604/49361392-54d85f00-f70a-11e8-854c-f66508c34ff0.png)
<img width="371" alt="screenhunter 212" src="https://user-images.githubusercontent.com/44358604/49361398-599d1300-f70a-11e8-9efc-8695ea5e2f90.png">

**Comment by asiamatrix** [comment]
Here is the 
<img width="359" alt="screenhunter 211" src="https://user-images.githubusercontent.com/44358604/49361434-6de11000-f70a-11e8-8a40-39ea4a0f18ae.png">
<img width="371" alt="screenhunter 212" src="https://user-images.githubusercontent.com/44358604/49361435-6de11000-f70a-11e8-937f-d8fd4473e3da.png">

security folder.

**Comment by Yenthe666** [comment]
Hmm looks good, you can open the file & there is no issues of corruption in the file?
In what language is your OS set? Perhaps that makes a difference, not sure, I'm just guessing at this point 😆

**Comment by Yenthe666** [comment]
Hmm really not sure then I'm sorry. I've had about 4 people in a few years that had this and they all had exactly the same issue. Nobody found a reproducable way or the issue though. I've got dozens of servers running with this module without any problems so there is not a lot I can do, sorry..
