### ISSUE TITLE
how to backup odoo12 running in docker 

### ISSUE THREAD

**Issue by ferdiga** [Yenthe666/auto_backup#121]
I tried 
* host: "my server name"
* port: 443

Error details:
<ProtocolError for my.server.at:443/xmlrpc/db: 400 Bad Request>

**Comment by ferdiga** [comment]
localhost and port 8069 as suggested produces a 0 byte backup file.

**Comment by Yenthe666** [comment]
@ferdiga it should work with the port of the Odoo and a correct path. The `list_db` parameter is set to true?
Is there anything in the logfile? I've never personally tested it on Docker.

**Comment by ferdiga** [comment]
the reason is:
DEBUG <dbname> odoo.addons.auto_backup.models.db_backup: Couldn't backup database <dbname>. Bad database administrator password for server running at http://localhost:8069 

docker version seems to auto generate a password which can/should  be retrieved from the /etc/odoo/odoo.conf file. ?

it seems to me that no password is used for xmlrpc ?!

**Comment by Yenthe666** [comment]
Hmm Docker shouldn't work differently from a local installed Odoo as far as I know. If you don't have or don't know the master password you should set one in the config file, restart the Odoo and then it should be applied.

**Comment by bileser** [comment]
It's just saying 'Bad database administrator password'

But the underlying error is permission denied

2020-02-18 11:16:50,304 1 DEBUG GFK odoo.addons.auto_backup.models.db_backup: Couldn't backup database GFK. Bad database administrator password for server running at http://0.0.0.0:8069
2020-02-18 11:16:50,304 1 DEBUG GFK odoo.addons.auto_backup.models.db_backup: Exact error from the exception: [Errno 13] Permission denied: '/home/backup/2020_02_18_11_16_50_GFK.zip'

Added this to my Dockerfile:

FROM odoo:11.0
USER root
RUN mkdir -p /home/backup
RUN chown odoo /home/backup
USER odoo

This is my docker-compose.yml:

version: '2'
services:
  web:
    build: .
    image: odoo_live
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - web:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      - backup:/home/backup
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db:/var/lib/postgresql/data/pgdata
volumes:
  web:
  db:
  backup:
    driver_opts:
      type: none
      device: /srv/backup
      o: bind

I configured auto_backup to save backups to /home/backup which is bind mounted to /srv/backup on the host

**Comment by yashu1wwww** [comment]
# For backup to another system:

# First, navigate inside the Odoo folder in the original system:
docker-compose down

# Next, execute the command to backup the files:
tar -cvzf odoo_backup.tar.gz -C /var/snap/docker/common/var-lib-docker/volumes odoo_odoo-db-data odoo_odoo-web-data

# Now, move the odoo_backup.tar.gz file to the new system:
tar -xvzf /home/student/Downloads/odoo_backup.tar.gz -C /var/snap/docker/common/var-lib-docker/volumes

# This means the file is now in the /home/student/Downloads folder.

# Then, create a folder named "odoo" and add the YAML file along with the odoo_pg_pass file (same as the file in the old system).

# After that, pull the Docker images:
docker pull odoo:16.0
docker pull postgres:15

# Ensure that it matches the docker-compose.yml file from the old system.

# Finally, start the containers:
docker-compose up -d

# Now you can access the running instance on localhost:8069.
