### ISSUE TITLE
[12.0] <Fault AccessDenied: 'Access denied'> 

### ISSUE THREAD

**Issue by gr22** [Yenthe666/auto_backup#123]
It throws an error if `list_db = False`  in config. This option is recommended in the docs for security.
It fails in `get_db_list()` because the config option forbids listing of databases
In V10 is the same

**Comment by Yenthe666** [comment]
Hi,

This is a known limitation of the module. I haven't found a clean way around it yet.

**Comment by gr22** [comment]
Oh, it's actually in the README, sorry for that!

**Comment by Yenthe666** [comment]
No problem 😉
