### ISSUE TITLE
[8.0] Error menu (not appear)

### ISSUE THREAD

**Issue by moblesmarti** [Yenthe666/auto_backup#124]
I have correctly installed the auto-backup module from Github in my Odoo 8, but it does not appear in the configuration menu. I've restarted my server several times, but it still does not appear.
I have also installed the necessary library and the Ubuntu system 16.04 correctly updated.

![image](https://user-images.githubusercontent.com/12881456/52282780-769bcf80-2961-11e9-83f4-ad9a467250e1.png)

**Comment by Yenthe666** [comment]
Hi,

Can you find it under the views and menu's? Do you have enough access rights?
Do you see your administrator user having rights on the table for the backups?

**Comment by gaikaz** [comment]
Could be related: #21, #60
(for anyone searching)

**Comment by Yenthe666** [comment]
Thanks @gaikaz

**Comment by moblesmarti** [comment]
Hello, I have done the following steps:
1. Uninstall Odoo module.
2. Delete module from the folder.
3. Restart odoo server.
4. Clear browser cache.
5. Download module, copy it to folder, with user and group odoo
6. Install module with Administrator user.

And everything goes the same, some idea? Thanks in advance.

![usuarios_-_odoo](https://user-images.githubusercontent.com/12881456/52332762-e494d500-29fb-11e9-89ef-46061da41d04.png)
