### ISSUE TITLE
[12.0] TypeError: $node is undefined

### ISSUE THREAD

**Issue by b46ol** [Yenthe666/auto_backup#125]
When i open menu "Schedulled Actions" and double clicks "Backup Scheduler" TypeError: $node is undefined

**Comment by gaikaz** [comment]
Why double click? Does it happen only with "Backup Scheduler"?
It looks like your error is JavaScript based. This module doesn't have any JS code. Could be some other module, probably something like back-end theme.

**Comment by Yenthe666** [comment]
It is probably a framework issue, your just seeing the symptom from it in my module but the cause comes from Odoo S.A. itself. You can probably trigger it with all other scheduled actions by clicking twice too.
