### ISSUE TITLE
Unnecessary copy of files

### ISSUE THREAD

**Issue by h4818** [Yenthe666/auto_backup#13]
Thank you for this great module - I love it!

I have 2 suggested improvements
1. User defined SSH port ( I see this has been done on master branch)
2. There is an unnecessary copy of files onto the sftp server. I know the module can be configured to work around this, however, I feel that one simple change improves the module and performance.

Before copying the file using `srv.put(pathToWriteTo)`
check if the file exists using `srv.exists(f)`

Without this, older backups are copied over to the sftp server every time the scheduler runs.

**Comment by Yenthe666** [comment]
Hi @h4818 

Thanks for your issue. The first suggestion is indeed in the master version, I'm not sure if I should migrate this in to the V8.0 one too though.
The second suggestion looks like a good and valuable one! This would indeed improve performance and would mean less data being transferred over the connection. I will try to test this soon so it could be added in the master version (and perhaps 8.0 too).

**Comment by Yenthe666** [comment]
Hi @h4818 

If I'm not mistaking you mean this:
```
#Loop over all files in the directory.
for f in os.listdir(dir):
    fullpath = os.path.join(dir, f)
        if os.path.isfile(fullpath):
            print(fullpath)
             if not srv.exists(f):
                 _logger.critical('This file is not yet on the remote FTP Server! Lets copy it.')
                 srv.put(fullpath)
            else:
                _logger.critical('This file already exists on the remote FTP Server!')
```

I've tried this a few times and seems to work just fine. Would you care to give this a try at your end too and have a look at how it works? This looks like a good fix :+1:

**Comment by Yenthe666** [comment]
@h4818 could you give this a try and provide me with feedback to please? :+1:

**Comment by h4818** [comment]
Hi @Yenthe666 ... this looks perfect thanks!

**Comment by Yenthe666** [comment]
Thanks for the report and feedback @h4818!
I'll merge this in to both versions within a few days. :smile:

**Comment by cysnake4713** [comment]
have this one been merge yet?
