### ISSUE TITLE
No backup file created

### ISSUE THREAD

**Issue by mockingbilal** [Yenthe666/auto_backup#132]
After successfull installation it is not creating any database backup file in the mentioned path.
Here are the screenshots for my configurations.
![image](https://user-images.githubusercontent.com/48237152/56890556-37c67300-6a93-11e9-9c52-268dfd4576f6.png)
![image](https://user-images.githubusercontent.com/48237152/56890581-4b71d980-6a93-11e9-836d-a8a064708de8.png)

**Comment by mockingbilal** [comment]
I forgot to mention, I have downloaded the module for v12 community and and running it on a VPS.

**Comment by Yenthe666** [comment]
You're trying to backup in a bit of an odd place though. Inside the packages, why?
Don't you have errors in the log that says the backup failed due to security issues or something?

**Comment by mockingbilal** [comment]
Yeah I had that errors as there was no directory found at that location, I have also tested that in the path location of "/home/odoo/backups" but still the issue is same.

I have defined the path because I want to have the backup on that specific folder.

And I am neither facing any error nor a backup file is creating.

**Comment by Yenthe666** [comment]
What does the logfile say when the scheduler goes off? There has to be something in your log.

**Comment by mockingbilal** [comment]
This is the latest request I made on clicking "Run Manually" button in the scheduled actions.
It is showing the same thing, it is just reading not writing, is there anything wrong I am doing?

![image](https://user-images.githubusercontent.com/48237152/57007744-6a43ad80-6c04-11e9-93db-4682fa75b458.png)

**Comment by Yenthe666** [comment]
Uhh there is not even something saying it is starting. Do you get the same output if you schedule the backup module its planner? Did you check all these https://github.com/Yenthe666/auto_backup#4-important-information ?

**Comment by mockingbilal** [comment]
![image](https://user-images.githubusercontent.com/48237152/57008352-e3dd9a80-6c08-11e9-8261-b8ae4d48c08c.png)

Yes I have checked everything you mentioned. I have also checked it with the auto planner, I have given a time over there and checked if it is creating a backup file but still same issue.

**Comment by Yenthe666** [comment]
Add some log statements in https://github.com/Yenthe666/auto_backup/blob/12.0/auto_backup/models/db_backup.py#L144 to check if it comes there.

**Comment by Dax1900** [comment]
Odoo 13 ce running on docker
I got the same issue as above:

2020-03-22 19:14:30,270 1 INFO Avunet13 werkzeug: 127.0.0.1 - - [22/Mar/2020 19:14:30] "POST /xmlrpc/db HTTP/1.1" 200 - 5 0.011 0.021                                                            
2020-03-22 19:14:30,276 1 INFO Avunet13 werkzeug: 172.17.0.1 - - [22/Mar/2020 19:14:30] "POST /web/dataset/call_button HTTP/1.1" 200 - 9 0.012 0.056                                             
2020-03-22 19:14:30,368 1 INFO Avunet13 werkzeug: 172.17.0.1 - - [22/Mar/2020 19:14:30] "POST /web/dataset/call_kw/ir.cron/read HTTP/1.1" 200 - 18 0.024 0.047                                   

During install I had to comply with the prerequisites:
sudo su -
docker exec -u 0 -it odoo bash
pip3 install paramiko
mkdir /odoo/backups
pip3 install pysftp

Now it seems to works without errors but no backups are created in /odoo/backups

**Comment by Dax1900** [comment]
I got the solution from another thread. Duh! I had to set the permissions on the folder:
chmod 775 \odoo\backups
chown odoo \odoo\backups

**Comment by Yenthe666** [comment]
775 might be a bit much maybe but that's up to you. Happy you found it!
