### ISSUE TITLE
Model not found: db.backup while installing 'auto_backup' module in 'odoo 12'

### ISSUE THREAD

**Issue by prajithpipt** [Yenthe666/auto_backup#136]
File "/home/ksoftodoo/odoo12/odoo/addons/base/models/ir_ui_view.py", line 275, in _inverse_arch
    view.write(data)
  File "/home/ksoftodoo/odoo12/addons/website/models/ir_ui_view.py", line 41, in write
    return super(View, self).write(vals)
  File "/home/ksoftodoo/odoo12/odoo/addons/base/models/ir_ui_view.py", line 444, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/home/ksoftodoo/odoo12/odoo/models.py", line 3284, in write
    self._write(store_vals)
  File "/home/ksoftodoo/odoo12/odoo/models.py", line 3430, in _write
    self._validate_fields(vals)
  File "/home/ksoftodoo/odoo12/odoo/models.py", line 1112, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.tools.convert.ParseError: "Error while validating constraint

Model not found: db.backup

Error context:
View `Configure Backup`
[view_id: 3010, xml_id: n/a, model: db.backup, parent_id: n/a]
None" while parsing /home/ksoftodoo/odoo12/custom_addons/auto_backup-10.0.10.0/auto_backup/views/bkp_conf_view.xml:4, near
<record model="ir.ui.view" id="view_backup_conf_form">
      <field name="name">Configure Backup</field>
      <field name="model">db.backup</field>
      <field name="type">form</field>
      <field name="arch" type="xml">
        <form string="Test">
	  <group col="4" colspan="4">
	    <separator col="2" string="Local backup configuration"/>
          </group>
	  <group>
	    <field name="host" colspan="2"/>
	    <field name="name"/>
	    <field name="port"/>
	    <field name="backup_type"/>
	    <field name="folder"/>
	    <field name="autoremove"/>
	    <field name="days_to_keep" attrs="{'invisible': [('autoremove','=',False)]}"/>
	  </group>
	  <group col="4" colspan="4">
	    <separator col="2" string="SFTP"/>
          </group>
          <div style="width:50%;border-radius:10px;margin: 10px 0px;padding:15px 10px 15px 10px; background-repeat: no-repeat;background-position: 10px center;color: #9F6000;background-color: #FEEFB3;" attrs="{'invisible': [('sftp_write','=',False)]}"><b>Warning:</b> Use SFTP with caution! This writes files to external servers under the path you specify.</div>
	    <group>
              <field name="sftp_write"/>
              <field name="sftp_host" attrs="{'invisible':[('sftp_write', '=', False)],'required':[('sftp_write', '=', True)]}"/>
              <field name="sftp_port" attrs="{'invisible':[('sftp_write', '=', False)],'required':[('sftp_write', '=', True)]}"/>
              <field name="sftp_user" attrs="{'invisible':[('sftp_write', '=', False)], 'required':[('sftp_write', '=', True)]}"/>
              <field name="sftp_password" attrs="{'invisible':[('sftp_write', '=', False)],'required': [('sftp_write', '=', True)]}" password="True"/>
              <field name="sftp_path" attrs="{'invisible':[('sftp_write', '==', False)],'required':[('sftp_write', '==', True)]}" placeholder="For example: /odoo/backups/"/>
              <field name="days_to_keep_sftp" attrs="{'invisible': [('sftp_write', '=', False)], 'required': [('sftp_write', '=', True)]}"/>
              <field name="send_mail_sftp_fail" attrs="{'invisible': [('sftp_write','=',False)]}"/>
	      <field name="email_to_notify" attrs="{'invisible':['|',('send_mail_sftp_fail', '==', False), ('sftp_write', '=', False)], 'required': [('send_mail_sftp_fail', '=', True)]}"/>
              <button name="test_sftp_connection" type="object" attrs="{'invisible': [('sftp_write','=',False)]}" string="Test SFTP Connection" icon="gtk-network"/>
            </group>
            <separator string="Help" colspan="2"/>
            <div>
              This configures the scheduler for automatic backup of the given database running on given host at given port on regular intervals.
              <br/>
	      Automatic backups of the database can be scheduled as follows: 
	      <ol>
		<li>
		  Go to Settings / Technical / Automation / Scheduled Actions.
		</li>
		<li>
		  Search the action named 'Backup scheduler'.
		</li>
		<li>
		  Set the scheduler to active and fill in how often you want backups generated.
		</li>
              </ol>
	      <p style="font-size:18px;">
		Need more help? <a href="mailto:yenthe.vanginneken@vanroey.be">Contact us!</a>
	      </p>
	  </div>
        </form>
      </field>
    </record>

**Comment by Yenthe666** [comment]
Hi,

You can actually see it is there (https://github.com/Yenthe666/auto_backup/blob/12.0/auto_backup/security/ir.model.access.csv)
There are multiple tickets regarding this but nobody was ever able to answer me what was different or wrong. See https://github.com/Yenthe666/auto_backup/issues/105 , https://github.com/Yenthe666/auto_backup/issues/119,  https://github.com/Yenthe666/auto_backup/issues/129,  https://github.com/Yenthe666/auto_backup/issues/130

As long as nobody gives me reproducable steps or the issue I cannot help. I have dozens of servers running with this module fine so it has to be something locally.

Regards,
Yenthe

**Comment by prajithpipt** [comment]
I seemed one more error while creating a database (the second one; already
have one) in centos 7 for odoo 12 CE

Error Message ;- " Database creation error: relation "ir_model" does not
exist LINE 1: SELECT * FROM ir_model WHERE state='manual' ^ "

I am using PostgreSQL-10


How to solve this, Please help me


Thank you

>

**Comment by Yenthe666** [comment]
It is not related to this module and you'll find dozens of reports related to this actually.
See https://github.com/odoo/odoo/issues/27575
https://www.odoo.com/fr_FR/forum/aide-1/question/error-when-installing-odoo-11-in-ubuntu-16-04-from-github-135096
https://stackoverflow.com/questions/54076327/odoo-12-error-you-dont-have-the-permission-to-access-the-requested-resource

and many more.
