### ISSUE TITLE
auto_backup module status ''To be installed" in Odoo 12

### ISSUE THREAD

**Issue by prajithpipt** [Yenthe666/auto_backup#137]
![photo_2019-06-19_16-48-07](https://user-images.githubusercontent.com/30921111/59764231-fc893900-92b8-11e9-9155-69541acfde00.jpg)

After restarting the Odoo service the auto_backup comes to apps store
but when I click the install button it will appear 'Cancel Install' as shown in the picture above 

note: odoo12CE installed in centos 7

what is the actual reason for this?
Please help me to resolve this

**Comment by Yenthe666** [comment]
The app version you have is absolutely not the V12 module. The icon on this app is back from V10 (see https://github.com/Yenthe666/auto_backup/blob/10.0/auto_backup/static/description/icon.png). V11 and V12 use another, new icon (https://github.com/Yenthe666/auto_backup/blob/12.0/auto_backup/static/description/icon.png) so I'm pretty sure you're trying to install an old version app on a newer Odoo version. :)
