### ISSUE TITLE
Install pysftp on odoo official docker image

### ISSUE THREAD

**Issue by BetaUliansyah** [Yenthe666/auto_backup#138]
Any one successfully install pysftp on [Odoo official docker image](https://hub.docker.com/_/odoo)? It uses debian as its base.

**Comment by Yenthe666** [comment]
I've never tested it on debian but you should be able to install the packages. What error or issue are you facing?

**Comment by BetaUliansyah** [comment]
After many trials, I found out this simple solution works.

`FROM odoo:10.0`
`USER root`
`RUN pip install -U pip`
`RUN pip install pysftp`

**Comment by Yenthe666** [comment]
Happy to hear you've got it working! Best of luck.
