### ISSUE TITLE
Not generating backups.

### ISSUE THREAD

**Issue by dsydnor** [Yenthe666/auto_backup#14]
The module is scheduled to run every 5 minutes. (For Testing)

There is nothing in log about it.
There is no backups in the backup folder.

**Comment by Yenthe666** [comment]
Hi @dsydnor,

Thanks for your report. Have a look at your logfile and see what it says about pysftp / the backup module. Another way to find your issues is by running the Odoo from your terminal, you'll see the errors being printed then.
I'm going to guess that this is a rights issue and that the relevant Odoo service user doesn't have enough rights on the location of the folder.

**Comment by dsydnor** [comment]
2015-08-17 05:10:21,217 6276 ERROR main1 openerp.addons.base.ir.ir_cron:
Call of self.pool.get('db.backup').schedule_backup(cr, uid, *()) failed in
Job 21
Traceback (most recent call last):
  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_cron.py", line 138,
in _callback
    getattr(model, method_name)(cr, uid, *args)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File
"/opt/odoo/.local/share/Odoo/addons/8.0/auto_backup/backup_scheduler.py",
line 144, in schedule_backup
    os.makedirs(rec.bkp_dir)
  File "/usr/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/odoo'

On Mon, Aug 17, 2015 at 1:52 AM Yenthe <notifications@github.com> wrote:

> Hi @dsydnor <https://github.com/dsydnor>,
>
> Thanks for your report. Have a look at your logfile and see what it says
> about pysftp / the backup module. Another way to find your issues is by
> running the Odoo from your terminal, you'll see the errors being printed
> then.
> I'm going to guess that this is a rights issue and that the relevant Odoo
> service user doesn't have enough rights on the location of the folder.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Yenthe666/auto_backup/issues/14#issuecomment-131687098>
> .
>
-- 
*Di'Juan Sydnor*
*VP, Online Sales & Services*
*Techies4Me, LLC*
*www.techies4me.com <http://www.techies4me.com/>*

**Comment by Yenthe666** [comment]
@dsydnor,

Exactly as I thought. Your problem is that the user that runs the Odoo service (and thus takes the backup and wants to store is) does not have enough access rights on the folder /odoo. You will need to make sure the Odoo service user has full read & write access to that folder and everything will work.

**Comment by dsydnor** [comment]
Looking at the /opt/odoo directory via sftp. It shows that the permissions
are drwxr-xr-x owner is odoo how can make it full read and write


On Mon, Aug 17, 2015 at 2:29 AM Yenthe <notifications@github.com> wrote:

> @dsydnor <https://github.com/dsydnor>,
>
> Exactly as I thought. Your problem is that the user that runs the Odoo
> service (and thus takes the backup and wants to store is) does not have
> enough access rights on the folder /odoo. You will need to make sure the
> Odoo service user has full read & write access to that folder and
> everything will work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Yenthe666/auto_backup/issues/14#issuecomment-131694740>
> .
>
-- 
*Di'Juan Sydnor*
*VP, Online Sales & Services*
*Techies4Me, LLC*
*www.techies4me.com <http://www.techies4me.com/>*

**Comment by Yenthe666** [comment]
You should use chmod to alter access rights on that folder (chmod 755 directory_name)

**Comment by dsydnor** [comment]
so the current permissions " drwxr-xr-x" are not correct?

On Mon, Aug 17, 2015 at 2:33 AM Yenthe <notifications@github.com> wrote:

> You should use chmod to alter access rights on that folder (chmod 755
> directory_name)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Yenthe666/auto_backup/issues/14#issuecomment-131695171>
> .
>
-- 
*Di'Juan Sydnor*
*VP, Online Sales & Services*
*Techies4Me, LLC*
*www.techies4me.com <http://www.techies4me.com/>*

**Comment by Yenthe666** [comment]
drwxr-xr-c means everyone can read the directory, but its contents can only be changed by the user. So looks like your Odoo user does not have enough rights to do everything on that folder. You could do  a chmod 777 to give every user full rights but this is seen as insecure in Linux. I don't know your whole setup so I don't know what exactly fits your needs. Anyways this has nothing to do with the module itself, this is an access right issue on user level.

**Comment by dsydnor** [comment]
I'm fairly new to Linux I'm sorry.. The owner behind the odoo server is
"odoo" .I'm running Ubuntu 14 on amazon cloud. The permissions on that
folder is now drwxrwxr-x in /opt/odoo

On Mon, Aug 17, 2015 at 2:45 AM Yenthe <notifications@github.com> wrote:

> drwxr-xr-c means everyone can read the directory, but its contents can
> only be changed by the user. So looks like your Odoo user does not have
> enough rights to do everything on that folder. You could do a chmod 777 to
> give every user full rights but this is seen as insecure in Linux. I don't
> know your whole setup so I don't know what exactly fits your needs. Anyways
> this has nothing to do with the module itself, this is an access right
> issue on user level.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Yenthe666/auto_backup/issues/14#issuecomment-131697904>
> .
>
-- 
*Di'Juan Sydnor*
*VP, Online Sales & Services*
*Techies4Me, LLC*
*www.techies4me.com <http://www.techies4me.com/>*

**Comment by Yenthe666** [comment]
No problem, I've been there and had that problem too. Let me get a full view here:
If I am correct you're trying to take SFTP backups on a remote server inside the folder /opt/odoo? 
If this is the case and there is no Odoo running on the remote server under that folder path you should give it a try to set the remote folder to full rights.
Something along these lines: chmod -R 777 /opt/odoo (-R means recursive and will give rights to everything within the folder /opt/odoo). Then try to take a back-up again.
Eventually you should ideally change your 777 to something else, since its not the most secure way.

**Comment by dsydnor** [comment]
I'm trying to setup backups on the same server as odoo at the moment.

On Mon, Aug 17, 2015 at 2:53 AM Yenthe <notifications@github.com> wrote:

> No problem, I've been there and had that problem too. Let me get a full
> view here:
> If I am correct you're trying to take SFTP backups on a remote server
> inside the folder /opt/odoo?
> If this is the case and there is no Odoo running on the remote server
> under that folder path you should give it a try to set the remote folder to
> full rights.
> Something along these lines: chmod -R 777 /opt/odoo (-R means recursive
> and will give rights to everything within the folder /opt/odoo). Then try
> to take a back-up again.
> Eventually you should ideally change your 777 to something else, since its
> not the most secure way.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Yenthe666/auto_backup/issues/14#issuecomment-131699149>
> .
>
-- 
*Di'Juan Sydnor*
*VP, Online Sales & Services*
*Techies4Me, LLC*
*www.techies4me.com <http://www.techies4me.com/>*

**Comment by Yenthe666** [comment]
Oh right so not even SFTP. Alright just do a chmod -R 777 on the correct folder and try a back-up again. It'll work.

**Comment by dsydnor** [comment]
Thank you kindly sir! So for remote backup i can only use ip for the host?

On Mon, Aug 17, 2015 at 2:57 AM Yenthe <notifications@github.com> wrote:

> Oh right so not even SFTP. Alright just do a chmod -R 777 on the correct
> folder and try a back-up again. It'll work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Yenthe666/auto_backup/issues/14#issuecomment-131699792>
> .
>
-- 
*Di'Juan Sydnor*
*VP, Online Sales & Services*
*Techies4Me, LLC*
*www.techies4me.com <http://www.techies4me.com/>*

**Comment by dsydnor** [comment]
Do the remote server must be sftp ready?

On Mon, Aug 17, 2015 at 3:02 AM Dijuan Sydnor <dijuan.sydnor@techies4me.com>
wrote:

> Thank you kindly sir! So for remote backup i can only use ip for the host?
>
> On Mon, Aug 17, 2015 at 2:57 AM Yenthe <notifications@github.com> wrote:
>
>> Oh right so not even SFTP. Alright just do a chmod -R 777 on the correct
>> folder and try a back-up again. It'll work.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Yenthe666/auto_backup/issues/14#issuecomment-131699792>
>> .
>>
> --
> *Di'Juan Sydnor*
> *VP, Online Sales & Services*
> *Techies4Me, LLC*
> *www.techies4me.com <http://www.techies4me.com/>*
>
-- 
*Di'Juan Sydnor*
*VP, Online Sales & Services*
*Techies4Me, LLC*
*www.techies4me.com <http://www.techies4me.com/>*

**Comment by Yenthe666** [comment]
You should provide the IP from the external host. If you want to work from a non-default port you should take the master version, it supports any port.
There should be SFTP support on the remote server.

**Comment by arafatx** [comment]
I know this issue has been closed and you follow an alternate way to store the backup. By looking at your setup (perhaps same like mine), you should change your backup path from

/odoo/backups to /etc/odoo/backup

make sure you chmod backup to:

cd /opt/odoo
mkdir backups
chmod 755 backups

done
