### ISSUE TITLE
[8.0]module not installed

### ISSUE THREAD

**Issue by sam-menara** [Yenthe666/auto_backup#143]
Hi,
First thank you for efforts.
I am a beginner on Odoo version 8 on Windows. I have to install Automated database backups module "auto-backup". I follow the same steps that you describesd, i copied the folder "auto-backup" version 8 into my addons folder. But when I try to run Odoo, I choose a database and that gives me the error in attached.  

If you have any suggestions please reply me.
![error](https://user-images.githubusercontent.com/55279234/64856980-3e591f80-d61b-11e9-8bb1-afb49ba6308f.png)

Thank you for you help.

**Comment by Yenthe666** [comment]
Hmm, I've had other windows users that seemed to have issues. Check the output of the logfile right after the restart of the service, that should mention the real issue.
