### ISSUE TITLE
sftp.isfile(path) error

### ISSUE THREAD

**Issue by SaravananSakthivel** [Yenthe666/auto_backup#144]
https://github.com/Yenthe666/auto_backup/blob/f6dfe26080e60fb633069aaab4e54dbb159c7335/auto_backup/models/db_backup.py#L249

- Error code -- sftp.isfile(fullpath)
- isfile function is not available for sftp connection
- Because of this remote directory backup file not getting deleted

**Comment by Yenthe666** [comment]
@SaravananSakthivel thanks for the report! Could you do a test by replacing `sftp.isfile(fullpath)` with `os.path.isfile(fullpath)` please? Does that work?

**Comment by SaravananSakthivel** [comment]
@Yenthe666 No It will not work since it is not in sftp connection mode.
You can commit as if (".dump" in file or '.zip' in file): because you are already listing files from the directory here https://github.com/Yenthe666/auto_backup/blob/f6dfe26080e60fb633069aaab4e54dbb159c7335/auto_backup/models/db_backup.py#L237 
As for as i concern, no need of checking sftp.isfile(fullpath)

**Comment by Yenthe666** [comment]
Sorry, I looked to fast through the code on mobile, I confused a few lines :-)
Did you run into this on V12? I assume that `if sftp.isfile(fullpath)` would work with `if file.isfile(fullpath)`?

**Comment by SaravananSakthivel** [comment]
@Yenthe666 No you cannot run with file. Since file is char here, it doesn't have isfile() function.I got this error with V12 only and my sftp system got crashed with overload of DB size. Then only i debugged the code found the cause.

**You can lookup here http://docs.paramiko.org/en/stable/api/sftp.html#**

Now i am not comparing isfile() and working with this change **if (".dump" in file or '.zip' in file):**

**Comment by Yenthe666** [comment]
Hmm I'm not sure, it is a bit risky because it can delete folders that way I believe? I should try to reproduce this I guess.

**Comment by SaravananSakthivel** [comment]
@Yenthe666 
But you are doing the loop for final directory here -- for file in sftp.listdir(pathToWriteTo): 

As per the code, I have come to know that you are copying the file(.dump or .zip) not directory to  **pathToWriteTo** location. So to conclude this **file** in sftp.listdir(pathToWriteTo) must be **.dump** or **.zip**.

If I am wrong correct me please.

**Comment by onlybigstone** [comment]
> https://github.com/Yenthe666/auto_backup/blob/f6dfe26080e60fb633069aaab4e54dbb159c7335/auto_backup/models/db_backup.py#L249
> 
> * Error code -- sftp.isfile(fullpath)
> * isfile function is not available for sftp connection
> * Because of this remote directory backup file not getting deleted

I meet the same problem “remote directory backup file not getting deleted”，what should i do？

**Comment by SaravananSakthivel** [comment]
@onlybigstone  you can directly use **if (".dump" in file or '.zip' in file):** instead of i**f sftp.isfile(fullpath) and (".dump" in file or '.zip' in file):** 

That is what i followed and working fine for me

**Comment by onlybigstone** [comment]
> @onlybigstone you can directly use **if (".dump" in file or '.zip' in file):** instead of i**f sftp.isfile(fullpath) and (".dump" in file or '.zip' in file):**
> 
> That is what i followed and working fine for me

Thanks a lot
