### ISSUE TITLE
Email on failure

### ISSUE THREAD

**Issue by nabilelkadiri** [Yenthe666/auto_backup#147]
Hi,

I would like to thank you first for your module, it is very helfull.

I'm trying to figure out where you can set to receive email notifications on failure, i'm not able to find the checkbox anywhere, as per the module description there is a box to tick in order to receive email notifications.

I'm using Odoo v10.0 CE.

Thank you

**Comment by nabilelkadiri** [comment]
I believe the issue is from the view : 

                    <group string="SFTP Settings">
                        <field name="sftp_host" placeholder="sftp.example.com"/>
                        <field name="sftp_port"/>
                        <field name="sftp_user" placeholder="john"/>
                        <field name="sftp_password"/>
                        <field name="sftp_private_key" placeholder="/home/odoo/.ssh/id_rsa"/>
                        <button name="action_sftp_test_connection" type="object" string="Test SFTP Connection" icon="fa-television"/>
                    </group>

There is a line missing with the email notification checkbox.

**Comment by Yenthe666** [comment]
Hi,

You can find it here in the view:
https://github.com/Yenthe666/auto_backup/blob/138085788acb69638838675064f1b7c89f5dfb74/auto_backup/views/backup_view.xml#L47-L49

The option is only built for SFTP failures.
