### ISSUE TITLE
 Connection Test Failed! Here is what we got instead: Raw

### ISSUE THREAD

**Issue by halonso1990** [Yenthe666/auto_backup#154]
Hello, this is a amazing plugin, but I am getting this error after trying to do on SFTP can you help me what's the meaning? Thanks Connection Test Failed! Here is what we got instead: Raw
Can you help me what's the meaning of this? thanks

**Comment by Yenthe666** [comment]
No idea honestly. Can you share how your configuration looks without posting the password/username please?
