### ISSUE TITLE
Cannot Show Menu in Settings

### ISSUE THREAD

**Issue by luismata01** [Yenthe666/auto_backup#163]
Hi

After install on Odoo 10.0 Auto Backup, this cannot show tool on Settings/Technical/Back-ups. And in Applications this show Installed.

Can you help me please

![image](https://user-images.githubusercontent.com/43929688/79744317-2265dc80-82d4-11ea-8724-4e77a8e35678.png)

**Comment by Yenthe666** [comment]
Have you given your user rights to this model? Configure it under the user.
