### ISSUE TITLE
Missing Settings Page in Odoo13

### ISSUE THREAD

**Issue by curtiskoelling** [Yenthe666/auto_backup#164]
Module has been installed and permissions given. I still can't find the settings for backups.
![image](https://user-images.githubusercontent.com/5056768/80027288-bf757080-84a0-11ea-9f4d-12b4d22eff24.png)

**Comment by Yenthe666** [comment]
Hi! Have you checked under Settings > Technical and do you have enough rights (as a user, besides of the auto backup access group)

**Comment by curtiskoelling** [comment]
Turns out you have to activate developer mode to access the Technical
settings in odoo13.
I found it and am good to go.

**Comment by Yenthe666** [comment]
Yeah exactly ;) It was hidden for safety purposes as it is a powerful feature. Have fun!
