### ISSUE TITLE
Permission denied" while evaluating 'model.schedule_backup()' with Docker deploy

### ISSUE THREAD

**Issue by daniel-lopez-4toangulo** [Yenthe666/auto_backup#165]
Hi, I'm getting the Permission denied error when using docker deploy

**Comment by Yenthe666** [comment]
Permission denied when writing backups or? Are you sure you have enough rights on the folders?

**Comment by daniel-lopez-4toangulo** [comment]
Sorry about my short description. I'm using docker, so, I have 3 containers, odoo, postgres and nginx and here is my first doubt. The backup directory is a path inside or ouside the odoo container ?. It looks like it's taking the outside directory. I have created a folder with 777 permission and yet I'm getting the same error.  The error is raised when executing manually the cron.

**Comment by Yenthe666** [comment]
It should take a directory within your operation system, so within your Docker container.

**Comment by daniel-lopez-4toangulo** [comment]
It was about permission the folder had 755 and I change it to 777 and it works. Thanks for your time and your quick responses
