### ISSUE TITLE
[12.0] Missing email fields

### ISSUE THREAD

**Issue by protontrigg3r** [Yenthe666/auto_backup#168]
Configuration fields to notify failed backups (_Auto. E-mail on backup fail_ and _E-mail to notify_) are missing.

**Comment by Yenthe666** [comment]
It's there:
https://github.com/Yenthe666/auto_backup/blob/79600404d12bd76ef5407942d73c4733c1faf999/auto_backup/views/backup_view.xml#L48-L49

**Comment by protontrigg3r** [comment]
I'm very sorry (I am using [auto_backup OCA](https://github.com/OCA/server-tools/blob/12.0/auto_backup/view/db_backup_view.xml) module), shame on me.

**Comment by Yenthe666** [comment]
Ahh that is why :) That's a spin-off from my one.
