### ISSUE TITLE
Error Connection to Remote Server Timed Out - Docker v13

### ISSUE THREAD

**Issue by andrewdhastings** [Yenthe666/auto_backup#169]
I just migrated a customer database to a new server using docker containers and they are using your backup module. However, now we are getting a timeout error that was not there before. 

Do you know if there needs to be a special setting for docker containers to use this module?

```
xxx.addons.auto_backup.models.db_backup: Error connecting to remote server! Error: timed out 
```
Thanks,

**Comment by Yenthe666** [comment]
Hmm not really but are you sure the config is correct and that the container can reach the remote server?

**Comment by andrewdhastings** [comment]
Sorry, it turned out to be a server config issue, the customer has both servers running on the same vLan (unknown to me), so I just used the local IP address and it worked perfectly. 

Thanks,
Andrew

**Comment by Yenthe666** [comment]
Aha! Well happy you've figured it out :)
