### ISSUE TITLE
Backup stopped working after DB grew to hundreds of MBs

### ISSUE THREAD

**Issue by tkontogi** [Yenthe666/auto_backup#170]
Hello. 

The module was installed successfully for Odoo 8.
It has been tested, it run for a long time, and also SFTPed to a remote server.

After the DB exited a size (unknown which one) the module stopped working.

Part of the log is:

[log.txt](https://github.com/Yenthe666/auto_backup/files/4697173/log.txt)

Also on test runs via the GUI I get the following error:

XmlHttpRequestError Proxy Error

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>502 Proxy Error</title>
</head><body>
<h1>Proxy Error</h1>
<p>The proxy server received an invalid
response from an upstream server.<br />
The proxy server could not handle the request <em><a href="/web/dataset/call_button">POST&nbsp;/web/dataset/call_button</a></em>.<p>
Reason: <strong>Error reading from remote server</strong></p></p>
</body></html>

/etc/odoo/openerp-server.conf has the following settings:

limit_time_cpu = 120
limit_time_real = 240

Thank you.

**Comment by Yenthe666** [comment]
Hmm.
1. Your log has concurrency & key errors, probably something you might want to look at
2. Your limit times are really short, are you sure it just doesn't have enough time to finish?
3. Are you sure the servers connection is being kept open long enough?

**Comment by tkontogi** [comment]
Thank you for your time to review the log and for the update.
Per item:

1. If they are not related to this issue, will take a look at different time. But thank you.
2. How should we estimate a per installation appropriate value set for the two parameters (limit_time_[cpu,real])?
3. I assume that the module will first create a local backup and then try to SFTP it to the remote server. If this is the case, then the problem is way before SFTPing, as there is no local copy of the backup ever created.

The last time a local backup was created, was about six months ago.

It could be useful to understand how the Proxy Error message relates to the status of the backup. The moment the error message shows up on screen, there is nothing more in the log apart from repetitions of:

2020-05-29 14:36:21,552 22902 INFO 20190117-PROD werkzeug: 127.0.0.1 - - [29/May/2020 14:36:21] "POST /longpolling/poll HTTP/1.1" 200 -
2020-05-29 14:36:22,929 22902 DEBUG ? openerp.service.server: cron0 polling for jobs
2020-05-29 14:36:31,878 22902 DEBUG ? openerp.service.server: cron1 polling for jobs
2020-05-29 14:37:22,993 22902 DEBUG ? openerp.service.server: cron0 polling for jobs
2020-05-29 14:37:27,225 22902 INFO 20190117-PROD werkzeug: 127.0.0.1 - - [29/May/2020 14:37:27] "POST /longpolling/poll HTTP/1.1" 200 -
2020-05-29 14:37:32,931 22902 DEBUG ? openerp.service.server: cron1 polling for jobs
2020-05-29 14:38:17,483 22902 INFO 20190117-PROD werkzeug: 127.0.0.1 - - [29/May/2020 14:38:17] "POST /longpolling/poll HTTP/1.1" 200 -
2020-05-29 14:38:23,065 22902 DEBUG ? openerp.service.server: cron0 polling for jobs
2020-05-29 14:38:33,981 22902 DEBUG ? openerp.service.server: cron1 polling for jobs
2020-05-29 14:39:07,714 22902 INFO 20190117-PROD werkzeug: 127.0.0.1 - - [29/May/2020 14:39:07] "POST /longpolling/poll HTTP/1.1" 200 -
2020-05-29 14:39:23,097 22902 DEBUG ? openerp.service.server: cron0 polling for jobs
2020-05-29 14:39:35,027 22902 DEBUG ? openerp.service.server: cron1 polling for jobs


Thank you once more.

**Comment by Yenthe666** [comment]
1. OK
2. Have a look at this doc: https://www.odoo.com/documentation/13.0/setup/deploy.html#id5
3. It indeed creates the backups locally first and then only starts the SFTP part so something is absolutely off there. If you manually trigger a backup nothing happens either? & There's nothing in the logs?

**Comment by tkontogi** [comment]
Nothing in the logs.. I am tailf'ing for the last 40 minutes after the backup manual trigger and there is nothing in the logs apart from the usual scheduled triggered entries (clean ups, e-mailing, system staff but nothing related to the backup) and cron0/1 polling for jobs.

Nothing else...

Open to help you to help me in any way advisable.

**Comment by Yenthe666** [comment]
Hmm that is super odd. Add some print/log statements at the very beginning of the function and see if they're shown.

**Comment by tkontogi** [comment]
This is the point were your "copy paste" guidance will be required. :)

I am good in sysadm' ing, but with zero coding dexterity especially with python.

Just tell me the file (relative or full) path and what to add approximately where in it.

My installation has the addon under: /opt/odoo/8/addons/auto_backup

**Comment by Yenthe666** [comment]
Haha sorry bud but I can't take your hand for every single step to debug/test, I'm on dozens of projects. ;)
Get your Odoo guy to check that out & help you.
You can add the print statements or log statements at https://github.com/Yenthe666/auto_backup/blob/f464b61e2d130913fd004674da6f26174e6f385c/auto_backup/backup_scheduler.py#L136

**Comment by tkontogi** [comment]
Noted will have them added (there is no odoo guy in this context - only a sysadmin - me).

However if you could at least let me know what exactly is required to be added (assuming it is single line), we could advance the issue.

Just some additional info. 
To be sure, the SFTP option was explicitly deactivated and still same behaviour.

Will come back with more detailed feedback.

Thank you for now.

**Comment by Yenthe666** [comment]
Add something like:
`_logger.error('We are starting the backup job')`
and then add a few every few lines further in. Restart, run the cron & check your logs.
