### ISSUE TITLE
after one month i errors from SFTPClient'

### ISSUE THREAD

**Issue by Dax1900** [Yenthe666/auto_backup#171]
I think it tries auto_backup try to delete a backupfile but cannot access it....
Thanks for your help

Dear,

The backup for the server localhost (IP: www.avunet.com) failed. Please check the following details:

IP address SFTP server: www.avunet.com
Username: xxxxx

Error details: 'SFTPClient' object has no attribute 'isfile'

With kind regards

**Comment by Yenthe666** [comment]
Err as far as I remember I don't have a single reference to "is_file" for SFTP. Are you sure that you're using my module & that it is the latest version? Else, can you point me to the origin please.

**Comment by gralet** [comment]
I guess it is the same problem as in https://github.com/Yenthe666/auto_backup/issues/144

**Comment by Yenthe666** [comment]
Oh yeah, right! Which version of pysftp are you running?

**Comment by gralet** [comment]
in my case : 
pysftp : 0.2.9
paramiko : 2.7.1
odoo : 13.0
Ubuntu : 18.04.4

**Comment by Yenthe666** [comment]
I assume that if you downgrade to 0.2.8 that you no longer have these issues?

**Comment by gralet** [comment]
I tried downgrading to 0.2.8, but same error.
Maybe the solution is to remove the condition "if sftp.isfile(fullpath)" as mentionned in https://github.com/Yenthe666/auto_backup/issues/144

**Comment by Yenthe666** [comment]
Resolved in https://github.com/Yenthe666/auto_backup/commit/4a3f3f2c36baaaee96c481ba972e148bdad9e22a
