### ISSUE TITLE
Error message when installing auto_backup modules

### ISSUE THREAD

**Issue by mm82299** [Yenthe666/auto_backup#177]
Hello,
I got this error message when installing the module auto_backup:
File "D:\Program Files (x86)\Odoo 11.0\server\odoo\addons\auto_backup\models\__init__.py", line 3, in <module>
    from . import db_backup
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\addons\auto_backup\models\db_backup.py", line 27, in <module>
    'This module needs paramiko to automatically write backups to the FTP through SFTP. Please install paramiko on your system. (sudo pip3 install paramiko)')
ImportError: This module needs paramiko to automatically write backups to the FTP through SFTP. Please install paramiko on your system. (sudo pip3 install paramiko)
2020-07-03 14:21:25,992 1068 INFO Test odoo.modules.loading: loading 1 modules...
2020-07-03 14:21:26,005 1068 INFO Test odoo.modules.loading: 1 modules loaded in 0.01s, 0 queries
2020-07-03 14:21:26,060 1068 INFO Test odoo.modules.loading: loading 38 modules...

I'm using odoo 11 installed on Windows 10

Any help please ?

**Comment by Yenthe666** [comment]
Did you install pysftp 0.2.8?

**Comment by mm82299** [comment]
Hello,
yes, I did
D:\odoo\pysftp-0.2.9>"C:\Python38\scripts\pip.exe" install pysftp
Requirement already satisfied: pysftp in c:\python38\lib\site-packages (0.2.9)
Requirement already satisfied: paramiko>=1.17 in c:\python38\lib\site-packages (from pysftp) (2.7.1)
Requirement already satisfied: cryptography>=2.5 in c:\python38\lib\site-packages (from paramiko>=1.17->pysftp) (2.9.2)
Requirement already satisfied: bcrypt>=3.1.3 in c:\python38\lib\site-packages (from paramiko>=1.17->pysftp) (3.1.7)
Requirement already satisfied: pynacl>=1.0.1 in c:\python38\lib\site-packages (from paramiko>=1.17->pysftp) (1.4.0)
Requirement already satisfied: six>=1.4.1 in c:\python38\lib\site-packages (from cryptography>=2.5->paramiko>=1.17->pysftp) (1.15.0)
Requirement already satisfied: cffi!=1.11.3,>=1.8 in c:\python38\lib\site-packages (from cryptography>=2.5->paramiko>=1.17->pysftp) (1.14.0)
Requirement already satisfied: pycparser in c:\python38\lib\site-packages (from cffi!=1.11.3,>=1.8->cryptography>=2.5->paramiko>=1.17->pysftp) (2.20)

**Comment by mm82299** [comment]
Exception: Module loading auto_backup failed: file auto_backup\security/ir.model.access.csv could not be processed:
 No matching record found for external id 'model_db_backup' in field 'Object'
Missing required value for the field 'Object' (model_id)
No matching record found for external id 'model_db_backup' in field 'Object'
Missing required value for the field 'Object' (model_id)

**Comment by mm82299** [comment]
Any Feedback please?
This is a quite urgent
Thanks

**Comment by Yenthe666** [comment]
Described on the front page in the main wiki at https://github.com/Yenthe666/auto_backup#44-no-matching-record-found-for-external-id-error 
See https://github.com/Yenthe666/auto_backup/issues/166
See https://github.com/Yenthe666/auto_backup/issues/152
See https://github.com/Yenthe666/auto_backup/issues/129
See https://github.com/Yenthe666/auto_backup/issues/119
See https://github.com/Yenthe666/auto_backup/issues/105
See https://github.com/Yenthe666/auto_backup/issues/92 
See https://github.com/Yenthe666/auto_backup/issues/65
