### ISSUE TITLE
Error details: 'SFTPClient' object has no attribute 'isfile' (Odoo v13)

### ISSUE THREAD

**Issue by andrewdhastings** [Yenthe666/auto_backup#178]
I'm getting the following error by email:

`Error details: 'SFTPClient' object has no attribute 'isfile'`

We have been running backups for a while now with no issues. However, we just started getting failers. 

Looking at the code, I'm guessing this has to do with the auto-delete which we have enabled? (timing lines up too, we have auto-delete after 30 days, and we have about 30 days worth of backups)

Any ideas on how to fix this? Did they change the library?

**Comment by Yenthe666** [comment]
I've removed this check at https://github.com/Yenthe666/auto_backup/commit/4a3f3f2c36baaaee96c481ba972e148bdad9e22a actually.
You could also test the PR from https://github.com/Yenthe666/auto_backup/pull/173

**Comment by andrewdhastings** [comment]
@Yenthe666 That did it. Thanks!

**Comment by Yenthe666** [comment]
@andrewdhastings good to hear, thanks!  Was it my removal you've tested or the other PR?

**Comment by andrewdhastings** [comment]
@Yenthe666 I just used your removal (current version) as I'm not personally worried about having .zip as a folder name.
