### ISSUE TITLE
auto_backup is stopping up gradations of all Installed modules

### ISSUE THREAD

**Issue by zamzamintl** [Yenthe666/auto_backup#182]
Dear Yenthe,
We are odoo enterprise subscriber. We were using your module perfectly in odoo 11 but after up gradation of our database to odoo 13  when we replace auto_backup v13 module it is stopping up gradations of all Installed modules. 
There is no error in log file. When we click to upgrade any module the system gone in to processing and terminated after sometime without any error. When we remove auto_backup module everything works perfect.
Need your help to resolve issue.
Thanks

**Comment by Yenthe666** [comment]
Hmm, odd that there is nothing in the logs. Some questions:
- Does the module create backups at any point?
- How is the backup configured?
- How is the scheduler configured?

**Comment by zamzamintl** [comment]
Thanks for your reply.
Problem has been resolved by changing database name and in backup configuration setting and by changing directory permission to user odoo.
