### ISSUE TITLE
no menuitem added for Backup Configuration

### ISSUE THREAD

**Issue by thomasklosinsky** [Yenthe666/auto_backup#19]
Hi Yenthe,
thank you for the great module.
I could install easily but unfortunately the menu item doesn not show up.

Odoo v8
branch 8.0 of your module.

server-log says:
openerp.modules.loading: module auto_backup: key 'update_xml' is deprecated in favor of 'data' for file 'bkp_conf_view.xml'.
openerp.modules.loading: module auto_backup: key 'update_xml' is deprecated in favor of 'data' for file 'backup_data.xml'.

Weird, isn't it?

**Comment by Yenthe666** [comment]
Hi @thomasklosinsky,

First of all, sorry for the late reply.. I lost this one out of sight!
Have you tried removing the module and reinstalling it? I honestly have no idea why you're getting this..

**Comment by thomasklosinsky** [comment]
@Yenthe666 ... ;) sure!
Also I tried it with completely removing data and then installing again. Loading all the modules in Odoo again, etc... no luck.
I mean, it's not too bad since I have a CentOS running and backup cronjobs, but would be nice to have though.

**Comment by Yenthe666** [comment]
@thomasklosinsky guess it has to do with this line: https://github.com/Yenthe666/auto_backup/blob/8.0/auto_backup/__openerp__.py#L46
perhaps you could rewrite it to the newer data way and perhaps that would work.

**Comment by Yenthe666** [comment]
Also see https://github.com/Yenthe666/auto_backup/issues/21
