### ISSUE TITLE
permission error while running scheduler manually

### ISSUE THREAD

**Issue by Mahnoorkhan025** [Yenthe666/auto_backup#194]
**I get this error when i run the scheduler manually. It is a permission error. even tough i gave this user 777 permission and tried changing owner too. Now i am not sure why this error is being encountered. Can you guide me through this?**

PermissionError: [Errno 13] Permission denied: '/home/ubuntu'
  File "/mnt/extra-addons/auto_backup/models/db_backup.py", line 152, in schedule_backup
    os.makedirs(rec.folder)
  File "/usr/lib/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
ValueError: <class 'PermissionError'>: "13
Permission denied" while evaluating
'model.schedule_backup()'

**Comment by Yenthe666** [comment]
You probably did a chmod on the wrong folder? Make sure the owner of the folder is the same as your `odoo` user and that it has enough rights. Show me the ls -l maybe

**Comment by Mahnoorkhan025** [comment]
![Uploading Screenshot from 2020-11-05 12-53-12.png…]()
drwxrwxrwx   2 root root  4096 Nov  5 06:44 backups

Backups is the folder in home directory with root as user and 777 permissions

**Comment by Yenthe666** [comment]
Well `root` is already obviously not your Odoo user so I'd change that plus I wouldn't use the "home" directory but use a dedicated folder :)

**Comment by Mahnoorkhan025** [comment]
i tried with ubuntu user and i used /home/ubuntu/backups? What should i use in place of these two? user and path?

**Comment by Mahnoorkhan025** [comment]
I apologize i am clearly annoying you but i did not understand it. I assume that the user we have mentioned in configuration is the one who can login into the server with specified ipv4 address and password. The user you have mentioned is odoo user (Database user) who lets assume is 'admin and password is ''admin". This is a bit confusing.

**Comment by Yenthe666** [comment]
I think we're mixing things here. Your Ubuntu user is not your user running Odoo (at least, normally it isn't). You probably have some user such at `odoo14` that runs Odoo.
On the local server you should make sure that the user that runs Odoo (e.g `odoo14`) has enough rights on the local folder (on this server) and is the owner of the folder. Then everything works fine, you're just having permission issues.
