### ISSUE TITLE
Auto Back Up on Odoo14 . Only login is Pvt Key and no password Login

### ISSUE THREAD

**Issue by powerpbpx** [Yenthe666/auto_backup#198]
Good day Yenthe666
Installed the autoback up but while configuring I can not connect to server with ssh private key . My Password option is not used in server . How can we configure the key in this sftp backup

Kind regards
Capt Anil Sharma

**Comment by Yenthe666** [comment]
Hi,

This is not really covered by default I'm afraid. You'd need to extend the module so it allows/verifies SSH keys.
