### ISSUE TITLE
V12 - No apparent error but no backup ...

### ISSUE THREAD

**Issue by 62ML** [Yenthe666/auto_backup#199]
Hello,
As I said, no apparent error but no backup made. This is all the more frustrating as for another instance, it works very well!
The parameters indicated in your doc. are correct ... I notice that the scheduler seems to work, the next executions are correct.
Context: 1) Odoo 12, Postgres, Docker 2) DBBackup Local disk: Docker Volume, the Odoo container has rw access to the external volume mounted )
No error and no dbbackup message in Odoo's log.
What can I do?
Sincerely,
Marc

**Comment by Yenthe666** [comment]
Hmm, that's not going to be an easy one to figure out. The easiest way is to probably add a few log statements throughout the cron job to see how far it goes and if it completes or not.

**Comment by 62ML** [comment]
Could you give me some indications so that I can insert these intructions? Thank you

**Comment by Yenthe666** [comment]
An example is in the source:
https://github.com/Yenthe666/auto_backup/blob/ab85c47bb1ce992f5e1001608f173a53afb26051/auto_backup/models/db_backup.py#L100
