### ISSUE TITLE
Custom port for SFTP

### ISSUE THREAD

**Issue by etatus** [Yenthe666/auto_backup#2]
It is needed a port field in the SFTP configuration form. I've implemented the changes locally (it is easy if you take the sftpip variable as base), so I can contribute if you wish.

**Comment by Yenthe666** [comment]
Hi Etatus!
Thanks for posting. Are you talking about a field where you can provide the external port for the FTP server? By default the SSH port is 22 so this is why I haven't thought about this..
So you'd like to be able to provide an external port in case the SSH port is not 22?

**Comment by etatus** [comment]
Yes, that's it. I needed to use a different port. The field can be set to 22 by default, but it should be editable. Pysftp connection accepts a port parameter, so it is easy to implement.

**Comment by lukebranch** [comment]
+1, 

This would definitely be a useful feature. I always put public facing SSH on an obscure port for security reasons. You are less likely to get people trying to brute force your SSH port if they can't find it on the most commonly used ports (eg. 22, 2200, etc.)

**Comment by Yenthe666** [comment]
+1 makes good sense. I'll have a look at this on thursday.
If I'm correct its simply changing
<code>srv = pysftp.Connection(host=ipHost, username=usernameLogin,
password=passwordLogin)</code>
to
<code>srv = pysftp.Connection(host=ipHost, username=usernameLogin,
password=passwordLogin,port=sftpPort)</code>
right? And then adding a field etc in the view.

**Comment by etatus** [comment]
Yes. You have to add a new column (integer) in the DB:

'sftpip': fields.char('IP Address SFTP Server', help="The IP address from your remote server. For example 192.168.0.1"),
'sftpport': fields.integer('Port SFTP Server', help="The port from your remote server. For example 22"),

You can also set sftpPort = 22 in _defaults structure.

Also be careful, because you have two "pysftp.Connection" in auto_backup.py.

I needed to restart the server after the changes (and maybe reinstall the addon).

**Comment by Yenthe666** [comment]
@etatus this is now available in the master version from this module. See https://github.com/Yenthe666/auto_backup/commit/a1b9583892c79c0a6c3b7ff83d3815ffbdfdac92
I'm not sure if I want to sync this into the V8 since its not adviced to change data models on already installed modules.. Could you give the master module a test and let me know if it works on your side too?
Any suggestion about merging this in to the V8 (stable) version are always welcome.
@lukebranch: Have a check? :+1:

**Comment by Yenthe666** [comment]
Tested this on two Ubuntu VM's and both worked. Closing this issue, please post back if anything should still be wrong.

**Comment by etatus** [comment]
Great! Sorry, I couldn't try this days....

**Comment by lukebranch** [comment]
@Yenthe666 ,

Same here, I just got back from China, so have not had the chance to test it properly yet. I'll test it extensively over the next couple of weeks and report back if I run into any issues.

**Comment by Yenthe666** [comment]
Okay great to hear, thanks guys! Keep me updated @lukebranch :)
Couldn't find any problems on my side anymore.
