### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by auditinfo** [Yenthe666/auto_backup#206]
hello,

i've tried to run the scheduled backup manually for testing it , but it was not working.i have got the error message below

raceback (most recent call last):
  File "/opt/odoo14/odoo/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo14/odoo/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: <class 'PermissionError'>: "13
****Permission denied" while evaluating
'model.schedule_backup()'****

i've gave all permissions but it still not working infortunatlly

thank you in advance

**Comment by Yenthe666** [comment]
Same as about 30 other, older, tickets:
https://github.com/Yenthe666/auto_backup/issues/192
https://github.com/Yenthe666/auto_backup/issues/176
https://github.com/Yenthe666/auto_backup/issues/32
And so on. There are not enough rights on the folder :)

**Comment by auditinfo** [comment]
hello Mr Yenthe

I've changed the path folder and it worked. thank you so much

regards
