### ISSUE TITLE
POS frontend displays auto_backup logger info

### ISSUE THREAD

**Issue by WTH70** [Yenthe666/auto_backup#209]
Odoo 13 CE - Ubuntu 20.04 LTS

I'm using Odoo 13 CE only for the Point of Sale (POS) module, and I'm using the auto_backup module (thank you @Yenthe666 ) to make a daily backup, both local and via SFTP to a remote server.

The POS frontend displays a _logger.info string (from db_backup.py) on a POS button.

<img width="421" alt="Screenshot POS" src="https://user-images.githubusercontent.com/89574962/130927947-f1a1ffa0-4784-4793-80cd-7be68a0cdcf3.png">

<img width="529" alt="Screenshot Inspect page" src="https://user-images.githubusercontent.com/89574962/130928590-3dc4e1f9-5c0d-422a-9445-9310530dea5d.png">

Any idea how to solve this?

**Comment by Yenthe666** [comment]
Sorry but for sure not related to our app :) We don't touch anything from POS and have no dependency/changes on any other model than our own. It looks like somebody in your system screwed up translation terms perhaps.
