### ISSUE TITLE
Menu 'Configure Backup' not fount v8

### ISSUE THREAD

**Issue by lammh** [Yenthe666/auto_backup#21]
After that the module is installed you will see a new menu item named ‘Configure Backup’ under Settings > Configuration.

Hello, I have no problem installing the Module
but I have not found the menu to configure Backup settings
![image](https://cloud.githubusercontent.com/assets/7395544/11112013/1f93ad20-890f-11e5-93fe-04ba6c284e83.png)

**Comment by Yenthe666** [comment]
@lammh I originally posted on my blog that this was due to not having admin rights but I see you have them now..
Please remove and re-install this module, I'm assuming it just didn't come through. Then refresh the whole page and it should show up.

**Comment by lammh** [comment]
Hello,
think's for your answer,
yes it's ok now i remove and re-install :+1:

**Comment by Yenthe666** [comment]
@lammh no problem, thanks for the feedback!
This seems to happen every once in a blue moon when something doesn't go 100% correct in Odoo. Good to hear its fixed.
