### ISSUE TITLE
Not working on Odoo.sh v. 14 

### ISSUE THREAD

**Issue by ahmadsherby** [Yenthe666/auto_backup#210]
Connection for External FTP server pass.
but when run the scheduler this message appears.

 File "/home/odoo/src/odoo/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: <class 'OSError'>: "30
Read-only file system" while evaluating
'model.schedule_backup()'

**Comment by ahmadsherby** [comment]
I solved this issue by adding the path from odoo sh  like : backup.daily/
but now the error for database connection

**Comment by Yenthe666** [comment]
See https://github.com/Yenthe666/auto_backup/issues/162 - it's an SH limitation and as of yet we don't really have a solution/workaround for it sorry!
