### ISSUE TITLE
odoo 15 auto back

### ISSUE THREAD

**Issue by jet1x** [Yenthe666/auto_backup#216]
I Have this error, i do not know how to fix it
![image](https://user-images.githubusercontent.com/79412804/147557886-f83f3069-0b91-4324-a407-5af97d98c110.png)

**Comment by Yenthe666** [comment]
I'm not sure why you've put (1) into the Python code? 🤔

**Comment by jet1x** [comment]
because i have 2 backups.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Στις Δευ 3 Ιαν 2022 στις 11:33 π.μ., ο/η Yenthe Van Ginneken <
***@***.***> έγραψε:

**Comment by Yenthe666** [comment]
That's totally not how the module works :) You are giving an argument to a function that does not need/allow one.

**Comment by jet1x** [comment]
i have done this on odoo 14 and it works

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Στις Δευ 3 Ιαν 2022 στις 12:22 μ.μ., ο/η Yenthe Van Ginneken <
***@***.***> έγραψε:
