### ISSUE TITLE
Change repository layout

### ISSUE THREAD

**Issue by crazybolillo** [Yenthe666/auto_backup#217]
I think it would be better if the module itself was in the root folder. That way I could clone the repo directly into my addons folder and install it. Right now if I clone the repo directly into my addons folder, Odoo does not detect the module, since the files are nested inside the folder. 

Right now the fix I'm going with is making a symbolic link, but the extra commands make my soul cry everytime I install this great module.

**Comment by Yenthe666** [comment]
@CrazyBolillo thanks for the suggestion. I built up the repository like this for adding possible extra modules/extensions actually.
I tend to always setup repositories like this so you can cleanly and easily add in multiple apps without breaking already running systems. The following setup in your Odoo config file should just work though?
```
/odoo/custom/addons/auto_backup
```

**Comment by crazybolillo** [comment]
Never considered that option, makes sense. 

Yes I could add it also add it to the addons path, although I prefer the symbolic link into my existing addons folders. Anyways I will close this since it seems it's just a matter of preference. Thanks for the chat.
