### ISSUE TITLE
Odoo 15: Backup Configuration successfully but no Backups!

### ISSUE THREAD

**Issue by bilalshehab** [Yenthe666/auto_backup#230]
Hi @Yenthe666 ,

Installed cleanly with no errors. Tried all method of configurations but there is no backup created on the desired storages.
With the well known that i have clicked "Run Manually" on Scheduled Actions.
Please advise.

Thank you

**Comment by Yenthe666** [comment]
Check the details of the log files :) Most likely an access error on the disks.

**Comment by bilalshehab** [comment]
> Check the details of the log files :) Most likely an access error on the disks.

Yes, it was the access error. Thanks alot.
