### ISSUE TITLE
Odoo 15 - Backup scheduler 

### ISSUE THREAD

**Issue by ecfsolutions** [Yenthe666/auto_backup#235]
Hello Yenthe,
if I try to adapt the scheduler (as it works with Odoo 11 CE) to use one of two config files I get the following error:

ValueError: <class 'TypeError'>: "schedule_backup() takes 1 positional argument but 2 were given" while evaluating
'model.schedule_backup(2)'

Is it my fault? Thanks for any hint.
Regards Christian

**Comment by Yenthe666** [comment]
You seem to be passing a parameter in the function while we do not accept one. See https://github.com/Yenthe666/auto_backup/blob/13457237de3020382f658f59aa02409296b17365/auto_backup/models/db_backup.py#L117
