### ISSUE TITLE
Which Time Zone is being used?

### ISSUE THREAD

**Issue by eHanse** [Yenthe666/auto_backup#24]
Hello Yenthe,

when I set up the backup via "Configure Backup", I have to set a time for the backup. Can you tell me which time zone is being used by the module?

My server is located in Hong Kong, but we are administrating it from Germany, so the admins time zone is Germany.

**Comment by Yenthe666** [comment]
@eHanse all times in Odoo are handled in UTC +0, so the back-up module should follow this exact behaviour

**Comment by eHanse** [comment]
Hello Yenthe, thanks for your quick reply.

I have also added a comment to your tutorial. I figured that the time you need to enter is the time zone of the user who activates the scheduled action. When I entered the servers time zone, nothing happened, but after I entered the user's timezone, I could see that the backup was done!

Brgds

**Comment by Yenthe666** [comment]
@eHanse,

No problem! I did see the comment, I haven't respond yet though. I do agree that the information could be slightly expanded so I'll place that on my to-do list for when I have some extra time.
It should take the time from the automated action, which is normally converted to an UTC +0 time.
