### ISSUE TITLE
Auto remove backups not working, odoo 13 community

### ISSUE THREAD

**Issue by porrasadrian** [Yenthe666/auto_backup#241]
Good morning, I have installed the autobackups module for a long time, and it worked perfectly, but for several days I have encountered the problem that even though I have selected the option auto remove backups and I have it selected in one day, It does not automatically delete the old backups, in the end without realizing it my storage fills up and the next backups to be generated are generated from 0...
The size of the backups that are generated at this moment are 4.3 GB, any solution?
Thanks and sorry for bothering!
Odoo 13 community

**Comment by Yenthe666** [comment]
See also https://github.com/Yenthe666/auto_backup/issues/187
