### ISSUE TITLE
'Configure Backup' submenu disturbs 'General Settings' [9.0]

### ISSUE THREAD

**Issue by mgielissen** [Yenthe666/auto_backup#26]
In v9.0 menu-item 'General Settings' has no submenu's anymore. This menu-item doesn't work anymore when auto_backup module is installed because this is a submenu-item.

A solution is to remove menu-item 'Configure Backup' as a submenu from 'General Settings'

**Comment by Yenthe666** [comment]
@mgielissen,

What exactly do you mean? It works just fine in V9? See this screenshot:
<img src="http://i.imgur.com/vQrA1Vr.png" alt="configuration screen"/>

**Comment by mgielissen** [comment]
Not in the community version

**Comment by Yenthe666** [comment]
@mgielissen does it throw up an error or?

**Comment by mgielissen** [comment]
@Yenthe666 Is doesn't give a error. General Settings doesn't work anymore when Configure Backup is a submenu from General Settings in v9c

**Comment by Yenthe666** [comment]
@mgielissen you're correct. It'll work in the V9 Enterprise but not under community. Could you perhaps supply a pull request to fix this please? I'm too busy to fix this for now..

**Comment by Yenthe666** [comment]
@mgielissen what do you think about this approach in ```bkp_conf_view.xml```:
```
<menuitem id="auto_backup_menu" name="Back-ups"  parent="base.menu_custom" sequence="0"/>
<menuitem parent="auto_backup_menu" action="action_backup_conf_form" id="backup_conf_menu"/>
```

The result in V9 community:
<img src="http://i.imgur.com/p5eisKi.png" alt="V9 Community"/>
The result in V9 Enterprise:
<img src="http://i.imgur.com/3gM0Lwz.png" alt="V9 Enterprise"/>

**Comment by mgielissen** [comment]
:thumbsup:

**Comment by Yenthe666** [comment]
Fixed @ https://github.com/Yenthe666/auto_backup/commit/5f6bb7ab8d13787f68a82d22d36bf9383ba208c6 for V9 community
