### ISSUE TITLE
[12.0] - Windows - Can users keep using Odoo while it is on backup process?

### ISSUE THREAD

**Issue by sound675** [Yenthe666/auto_backup#279]
Hi @Yenthe666 
Thank you for your addon. It has been working well and no problem. =)
I really appreciate your time and should you have a spare / free time, could you please kindly reply my questions as follows :

**1. I am using Windows for Odoo 12.**
The auto_backup addon is working well. However, can the users keep accessing database ( making new Invoices, new records, etc ) while it is on backup process? ( I am have set the time for automatic schedule backup )
Or would it be better is the user stops working while the auto_backup is doing backup ?
Please Advice.

**2. Currently, the database is reaching 15GB ( I do Automated Backup daily )**
I have been reading your github that there are some cases whereas the cron time is 'not enough'. as your reply as follows : 
"_This can happen if you have a big database and your cron times out before it finishes. In this case it will re-try again and the same loop seems to go off again._"

source : https://github.com/Yenthe666/auto_backup/issues/187

My database is bigger daily and after reading this information I set in my odoo.config as follows : 
limit_time_real = None
limit_time_real_cron = None
max_cron_threads = 2

Is this appropriate ?  ( I presume with Windows, any changes that I do on odoo.config will not have any effects )
Please advice your feedback / insights about Odoo Config in Windows.

I thank you for you kind attention

**Comment by Yenthe666** [comment]
Hi,

1. Well that is up to you :-) Just know that the backup is a snapshot so anything entered after the backup is generated would be missing but that is typical behaviour. I don't see more issues there.
2. It should work but it can be that at some point the package or resources of your computer will time-out/halt and then your database will not be completed and corrupt.

**Comment by sound675** [comment]
Hi @Yenthe666 

1. Well Noted =)

2. Noted, in that case I conclude the solution is : To scale up / update components of the computer **continually**, as the data size will continue to grow. 
Goal : to make sure the resources of the computer able to accommodate the ever growing database, right?

Thank you so much for your feedback and time for replying my message from a newbie such as me. 
I really appreciate it and very thankful.

**Comment by Yenthe666** [comment]
for 2: yes probably :)
Anytime. Forgive me for short replies, I have quite some projects/teams to manage so I try to help as efficient as possible.
