### ISSUE TITLE
Increase the Chinese translation of documents,

### ISSUE THREAD

**Issue by talway** [Yenthe666/auto_backup#3]
Hello
1. Increase the Chinese translation of documents,
2, is only part of your document, if I can not be translated to other translations are made available, 

Can be made of the following places, such as the translation of documents in 
auto_backup\i18n\zh_CN.po

such as:

Local backup configuration 
Auto. Remove Backups

Warning: Use SFTP with caution! This writes files to external servers under the path you specify.

Write to external server with sftp

Automatic backups of the database can be scheduled as follows:

    Go to Settings / Technical / Automation / Scheduled Actions.
    Search the action named 'Backup scheduler'.
    Set the scheduler to active and fill in how often you want backups generated. 

Need more help? Contact us!

**Comment by Yenthe666** [comment]
@talway I'm sorry but I am not sure what you mean. If I understand correctly you're asking for translations in Chinese for my module?
You could add a file zh_CN.po and make all your translations there. If you have them working and wish to add them to the module you're more than welcome to create a pull request. I'll test them and if they work I will add them to the module!

Please rephrase your question if you ment something else.
Yenthe

**Comment by talway** [comment]
1, yes, the Chinese translation to add me in your file there, please test;

2, in addition: other statements, can also be made into translation, in the Po file

**Comment by Yenthe666** [comment]
@talway I will test your translations tommorow or on friday and I'll post back. If they work I'll update the file. Thanks for the contribution! :)

**Comment by talway** [comment]
OK, thank you


In addition: other statements, didn't find me in your PO file, whether can you also do other statements in the Po file, so I am Chinese translation.


For example：

Local backup configuration
Auto. Remove Backups
Warning: Use SFTP with caution! This writes files to external servers under the path you specify.
Write to external server with sftp
Automatic backups of the database can be scheduled as follows:
Go to Settings / Technical / Automation / Scheduled Actions.
Search the action named 'Backup scheduler'.
Set the scheduler to active and fill in how often you want backups generated. 
Need more help? Contact us!

**Comment by Yenthe666** [comment]
@talway yes I should update the default PO file for one language, since they only contain a part of the text. This is on the 'to-do' list but takes rather a lot of time and does not have a lot of functionality.
If you have time and/or want to contribute you're always welcome. 

It is on the To-Do list to add all text in the PO file though! :+1:

**Comment by talway** [comment]
Good, but you need to give me a specific example, teach me how to do the translation of documents; so that I can go to the actual operation, thank you.

**Comment by Yenthe666** [comment]
@talway I've updated all translations for English and Dutch. I've tested your translations and they worked perfect but it is only a slight part. Therefor I've updated the whole auto_backup.pot file and this now contains any text in my module. You can find this here: https://github.com/Yenthe666/auto_backup/blob/8.0/auto_backup/i18n/auto_backup.pot
Could you please copy everything that is inside this file, paste it in your zh_CN.po file and create your Chinese translations? That way I have a fully, perfect, translated module in Chinese and not just some part (with some outdated text).
If you need an example look at the file https://github.com/Yenthe666/auto_backup/blob/8.0/auto_backup/i18n/nl.po this is a fully translated language for the module.

Thanks! :+1:

**Comment by Yenthe666** [comment]
Added the translations from @talway here: https://github.com/Yenthe666/auto_backup/commit/27c7c845b575e0dbbc0923564cff94fd57d00eb1
Thanks for contributing!
