### ISSUE TITLE
Backup to ftp server

### ISSUE THREAD

**Issue by zimbar** [Yenthe666/auto_backup#34]
Hy,

How can i backup to ftp server, and which port do i make (21,22)?

Thanks

**Comment by Yenthe666** [comment]
@zimbar just fill in the FTP server its IP and settings. The port depends on which OS and your configuration. By default Linux uses port 22 for FTP.

**Comment by zimbar** [comment]
Thank you for your reply, but the backup to an FTP server does not work for me and the port is usually 21, 22 is for sftp normally.

**Comment by Yenthe666** [comment]
@zimbar I'll need a detailed log to help you any further to what the issue is. 
As for SFTP: see this https://github.com/Yenthe666/auto_backup/blob/8.0/README.md 
If you need another port you should download the 9.0 version.

**Comment by Ark74** [comment]
Port 22, really?
I thought 22 was ssh.

Mmm, interesting.
So, can I use v9.0 on a 10 installation if I need to use port 21?
