### ISSUE TITLE
Bug with installing pycrypto

### ISSUE THREAD

**Issue by diezcode** [Yenthe666/auto_backup#36]
auto_backup module with the current debian package installation of odoo8 is not working

**Comment by Yenthe666** [comment]
@diezcode very hard to tell by what you've placed here.. Which command did you issue to install pysftp?

**Comment by diezcode** [comment]
first of all this:

sudo pip install pysftp

then this

sudo apt-get install python-pip

**Comment by Yenthe666** [comment]
@diezcode I see nothing that could throw up a problem with pysftp :confused: 
No idea where that pycrypto issue is coming from.

**Comment by diezcode** [comment]
can it be that there is any port or firewall problem with that?

**Comment by Yenthe666** [comment]
@diezcode the only thing I can think of is that you don't have SSH opened and want to back-up through SSH.. I'm not sure about your networking setup though, this is a way to broad question to help you with I'm afraid :person_frowning:
