### ISSUE TITLE
Back up was working fine and then suddenly stopped

### ISSUE THREAD

**Issue by eng-eslam-a-y** [Yenthe666/auto_backup#37]
i'm running  a cloud server with different installation of odoo servers and all backups are working fine except on project , it's backup was working fine till 08-02-2016 and with no reason stopped i just noticed now , the backup is scheduled every day at 18:00:00 GMT
here is the log file :
ERROR xxxx openerp.addons.base.ir.ir_cron: Call of self.pool.get('db.backup').schedule_backup(cr, uid, *()) failed in Job 11
Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo_xxxxx\server\openerp\addons\base\ir\ir_cron.py", line 138, in _callback
  File "C:\Program Files (x86)\Odoo_xxxxx\server\.\openerp\api.py", line 250, in wrapper
  File "C:\Program Files (x86)\Odoo_xxxxx\server\openerp\addons\auto_backup\backup_scheduler.py", line 155, in schedule_backup
NameError: global name 'logger' is not defined

**Comment by Yenthe666** [comment]
@eng-eslam-a-y rather strange that this is going off al of a sudden. The easiest fix is to remove all logger statements in the Python file `backup_scheduler.py` and to reload your module. This should remove all issues.

**Comment by jaronemo** [comment]
Dears

![image](https://cloud.githubusercontent.com/assets/8476734/14534821/6d3bab24-029d-11e6-9dbf-3220d0d8149a.png)
some problem...how can i do?

**Comment by Yenthe666** [comment]
As stated one comment above yours. Remove everything regarding logging and re-install the module. This should remove the issues.

**Comment by onduex** [comment]
FYI
I has a server that auto backup was running well, and when I have change Odoo to another better, auto backup stop running as as above.
Thanks,
