### ISSUE TITLE
[9.0][Ubuntu 14.04.4 LTS]Unable to install pysftp

### ISSUE THREAD

**Issue by treviser** [Yenthe666/auto_backup#40]
Hi Yenthe
"sudo pip install pysftp" does not work. It says it's succesfully installed, but it is not. I've found out that paramiko is also necessary and not automatically installed. I did 
"sudo apt-get install python-paramiko", it installed successfully.
But the error message of the module did not disappear. So I opened a python session and tried to import pysftp, and this is what I get:

>>> import pysftp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pysftp.py", line 10, in <module>
    import paramiko
  File "/usr/local/lib/python2.7/dist-packages/paramiko/__init__.py", line 30, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 33, in <module>
    from paramiko import util
ImportError: cannot import name util
>>>

Now I'm stuck because I have no idea where to get this "util" from. Any advise?

**Comment by Yenthe666** [comment]
@treviser what exactly do you mean with sudo pip install pysftp does not work? When I do this on a clean Ubuntu:
![image](https://cloud.githubusercontent.com/assets/6352350/14039626/a07ed32a-f25e-11e5-9331-cac9670c15a7.png)

It should work out of the box!

**Comment by treviser** [comment]
After all I tried, such as installing paramiko separately etc. now I did a "sudo pip install pysftp" again and now it works, don't ask me why...
Thanks anyway and happy Eastern!

**Comment by Yenthe666** [comment]
@treviser perhaps somebody made an error in the package yesterday or something. :smile: 
I'm glad to hear it is working again, happy easter for you too!
