### ISSUE TITLE
Backup Failures

### ISSUE THREAD

**Issue by mrparadies** [Yenthe666/auto_backup#46]
So I have been using for the last month or so with mixed results.  I am on V9 enterprise.  The backups will work fine for about a week and then they just stop working.  I have setup a cron job to stop the odoo service right before backup and that seems to help, but I am still missing backups.  Here is the error I see in the odoo log:

016-06-28 05:01:08,806 23340 ERROR  openerp.addons.base.ir.ir_cron: Call of self.pool.get('db.backup').schedule_backup(cr, uid, _()) failed in Job 14
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/openerp/addons/base/ir/ir_cron.py", line 129, in _callback
    getattr(model, method_name)(cr, uid, *args)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, *_kwargs)
  File "/opt/odoo/custom-addons/auto_backup/backup_scheduler.py", line 147, in schedule_backup
    db_list = self.get_db_list(cr, user, [], rec.host, rec.port)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/custom-addons/auto_backup/backup_scheduler.py", line 59, in get_db_list
    db_list = execute(conn, 'list')
  File "/opt/odoo/custom-addons/auto_backup/backup_scheduler.py", line 46, in execute
    raise e
error: [Errno 111] Connection refused

My backup is coming in around 500mb.  Any idea whats going on?

**Comment by Yenthe666** [comment]
Hi  @mrparadies,

That is strange. Do you experience the problem with other db's too? Did you find any common factor that influences this?
Possibly related to this one too: https://github.com/Yenthe666/auto_backup/issues/45

**Comment by mrparadies** [comment]
I only have a single database on my live server so its difficult to say.  I have tried to narrow down whats causing this but just cant seem to figure it out.  I am running it at a time no one is on the system and I dont think anything else is running.

**Comment by Yenthe666** [comment]
Hi @mrparadies,

Could you add another log statement here?
https://github.com/Yenthe666/auto_backup/blob/8.0/auto_backup/backup_scheduler.py#L46
Add a new line for the socket.error and please let me know what that throws up?
