### ISSUE TITLE
No hostkey?

### ISSUE THREAD

**Issue by diezcode** [Yenthe666/auto_backup#47]
I get this error, how can I fix that?

Here is what we got instead:
No hostkey for host backup.myserver.ch found.

But I think my configuration is correct, because I have other servers that works fine with this module

**Comment by Yenthe666** [comment]
Hi @diezcode,

Have a look at these topics: https://www.google.be/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=no+hostkey+for+host

**Comment by diezcode** [comment]
I found the problem thank you @Yenthe666 
I added to the ssh_config file this:
`StrictHostKeyChecking no`

**Comment by Yenthe666** [comment]
Perfect, good luck!

**Comment by diezcode** [comment]
hm the problem is still coming up mate,
I try to put this in your module, It seems like in pysftp 0.2.9 it needs a hostkey.
`import pysftp
cnopts = pysftp.CnOpts()
cnopts.hostkeys = None
with pysftp.Connection('host', username='me', password='pass', cnopts=cnopts):
    # do stuff here`

http://pysftp.readthedocs.io/en/release_0.2.9/cookbook.html#pysftp-cnopts

What you think?

**Comment by Softdil** [comment]
Having the same problem here... Nothing worked out for me.

**Comment by Yenthe666** [comment]
Hi @diezcode and @Softdil could you guys give this a try please? http://stackoverflow.com/questions/10670217/paramiko-unknown-server
In the past Paramiko / Pysftp worked just fine but now it looks like you need an explicit call for the keys:
`client.load_system_host_keys()`

**Comment by diezcode** [comment]
@Yenthe666 and where should I write this code? in which file?

**Comment by Yenthe666** [comment]
@diezcode in backup_scheduler.py, somewhere right before the connection is started. https://github.com/Yenthe666/auto_backup/blob/8.0/auto_backup/backup_scheduler.py#L119

**Comment by diezcode** [comment]
with this code it isn't working for me:

import paramiko

paramiko.util.log_to_file('ssh.log') # sets up logging

client = paramiko.SSHClient()
client.load_system_host_keys()
client.connect('127.0.0.1', username=username, password=password)
stdin, stdout, stderr = client.exec_command('ls -l')

or

import paramiko

client = paramiko.SSHClient()
client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
client.connect('127.0.0.1', username=username, password=password)
stdin, stdout, stderr = client.exec_command('ls -l')

I really don't know what's wrong ;(

**Comment by diezcode** [comment]
I fixed it ! I have changed the pysftp 0.2.9 to 0.2.8 the older version and it works fine!
I think the problem is with this log:
https://pypi.python.org/pypi/pysftp

added pysftp.Connection.remote_server_key - used to retrieve the remote hosts server key.

**Comment by Yenthe666** [comment]
Hmm it looks like it has to do with version 0.2.9 and the fix for the hostkey indeed.. well, guess a downgrade is fine.

**Comment by Softdil** [comment]
Confirmed, thank you @diezcode

**Comment by salmemik** [comment]
What is correct way to do the downgrading, could you please help. Thanks!

root@Ubuntu-1604-xenial-64-minimal ~ # sudo apt-get update
....                   
Reading package lists... Done

root@Ubuntu-1604-xenial-64-minimal ~ # sudo apt-get install pysftp=0.2.8
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package pysftp
root@Ubuntu-1604-xenial-64-minimal ~ #

**Comment by artschwagerb** [comment]
@salmemik 
pip install pysftp==0.2.8

**Comment by Ark74** [comment]
Hi!
So after installing the module, and I face this issue the only change I need to apply is the downgrade?

Or also changing stuff at paramiko  I got confused?

**Comment by Yenthe666** [comment]
A downgrade should do the job. :)

**Comment by Ark74** [comment]
Finally got the chance to test it. 
Great! Thanks.

**Comment by 88-it** [comment]
I did pip install pysftp==0.2.8 to downgrade, the downgrade worked but still have the issue (I m using Odoo 8), any idea how to fix it?

Thanks for your reply

**Comment by 88-it** [comment]
I've got an issue I resolved by following : https://askubuntu.com/questions/790116/python-pip-install-xmltodict-fails

and then I only have to reboot and reloging to Odoo

Everything is working fine now

**Comment by johnmoxon** [comment]
Thanks! Downgrade worked for me too.  Looks like this package no longer developed (at least no releases since July 2016) so 0.2.8 it is!

**Comment by joriatyBen** [comment]
Thanks, it worked. @Ark74 : has nothing to do with Paramiko as far as i know. I use Paramiko in another project and with multiple hosts, never had a problem with hostkeys.

**Comment by GrupoAlvamex** [comment]
@artschwagerb  Thank you!!! It's work for me: 
pip install pysftp==0.2.8

**Comment by fedimad** [comment]
No hostkey for host xxx.xxx.xxx.xxx ....
In my case I have more then 30 servers in different states, sometimes it works withe `pysftp 0.2.9` and sometimes i had to downgrade to `0.2.8`
the only way is to use `paramiko`, or just download the module on its version 11.0 and  install it on version 10 instance

**Comment by nchandra-seg** [comment]
Looks like there is no proper solution using 0.2.9. Will this be fixed in near future?
