### ISSUE TITLE
Backup failing on a restored database

### ISSUE THREAD

**Issue by mercadolino** [Yenthe666/auto_backup#49]
Hello Yenthe666,
first of all I'd like to thank you for your module. I chosed it over all the alternatives that I found so far. I've just spent two days trying to figure out what is causing an issue with it but so far I could find a solution.
What I am doing is:
1. Launch an EC2 instance with ubuntu 14.04
2. Deploy odoo v8
3. Create a test database and setup auto_backup
4. Setup the scheduling and backup WORKS FINE (so far)!
5. restore a production database (~60MB)
6. Schedule a backup and I get:
logger.notifyChannel('backup', netsvc.LOG_INFO, "Couldn't backup database %s. Bad database administrator password for server running at http://%s:%s" %(rec.name, rec.host, rec.port))

To try if the admin_passwd is working I am performing a backup with the web utility (/web/database/manager) and it is working fine.

**Comment by mercadolino** [comment]
this is the exact output from odoo logfile:

2016-08-17 19:15:24,724 24943 ERROR ademedia openerp.addons.base.ir.ir_cron: Call of self.pool.get('db.backup').schedule_backup(cr, uid, *()) failed in Job 10
Traceback (most recent call last):
  File "/opt/odoo/odoo/openerp/addons/base/ir/ir_cron.py", line 138, in _callback
    getattr(model, method_name)(cr, uid, *args)
  File "/opt/odoo/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/custom/addons/auto_backup/backup_scheduler.py", line 156, in schedule_backup
    logger.notifyChannel('backup', netsvc.LOG_INFO, "Couldn't backup database %s. Bad database administrator password for server running at http://%s:%s" %(rec.name, rec.host, rec.port))
NameError: global name 'logger' is not defined

**Comment by 3stratum** [comment]
Just an FYI, I believe I have the same issue as we are unable to backup using this tool.   Just about all of our databases are restored from backup so this could be the same.  The admin_password is correct.

Of course, looking at the code, it just always throws this same error message if the backup fails so it might have nothing to do with admin_password.

**Comment by Yenthe666** [comment]
Hi guys,

Sorry for the delay on this. The main issue here was `notifyChannel` and `logger` instead of `_logger.critical`. This is fixed (well, removed) in V9 and V10. If you want to fix this for you you can change the code in your own module. 
If you still face it after changing this you should be getting a better error message with details. if this is the case then please post back with the info!

Regards,
Yenthe

**Comment by aziechang** [comment]
I increased the swap size and solved this problem.  Add more RAM or more SWAP.

hope this helps.
