### ISSUE TITLE
[Master] Install failure on Odoo10.0

### ISSUE THREAD

**Issue by fenshuajiang** [Yenthe666/auto_backup#50]
![issue](https://cloud.githubusercontent.com/assets/7471985/19220536/19e07c7e-8e62-11e6-96ec-789f50021836.png)

**Comment by Yenthe666** [comment]
Hi @fenshuajiang,

Thank you for your report.
At this point the module is not yet fully migrated to the new API and it is not (yet!) available for V10.

Regards,
Yenthe
