### ISSUE TITLE
 Odoo10 what time can be used, look forward to!

### ISSUE THREAD

**Issue by talway** [Yenthe666/auto_backup#52]
Odoo10 what time can be used, **look forward to!**

**Comment by Yenthe666** [comment]
Hi @talway,

If you're asking when the module is ready for V10 I have to say I'm not sure.
I need to find some extra time to migrate everything to the new API but I don't have any spare time at this point. Perhaps in a few weeks.

**Comment by talway** [comment]
Thank you very much for your contribution, I will wait
