### ISSUE TITLE
Odoo8 Backup Problem with Bad authentication type

### ISSUE THREAD

**Issue by diezcode** [Yenthe666/auto_backup#57]
I'm having trouble with this error message:

Verbindungstest fehlgeschlagen!
Here is what we got instead:
Bad authentication type
[u'publickey', u'gssapi-keyex', u'gssapi-with-mic', u'keyboard-interactive']

I have configurate a ftp connection setting. 
Is there anyone that can help me with this? 

I think there is a problem that auto_backup module try to make an sftp connection and my server has it on ftp?

Thank you

**Comment by Yenthe666** [comment]
Hi @diezcode,

This looks like an inconsistency in protocols. The module needs SFTP, while yours runs on FTP.
The both cannot communicate with eachother and only SFTP is allowed because of security reasons.
Just make your remote location available by SFTP 😉 

Regards,
Yenthe
