### ISSUE TITLE
Access rule missing

### ISSUE THREAD

**Issue by ruifranco** [Yenthe666/auto_backup#60]
v10

The module creates no access rule for the db.backup model. This causes the menu not to show (at least in a "copy" of the admin user).

I had to create a rule for the Admin/Settings group.

**Comment by Yenthe666** [comment]
Hi @ruifranco,

Thank you for the report and sorry for the delay.
The reason there is no security rule is that I initially only wanted this to be visible for the admin user. I still don't really see a reason to change this as only the admin user should be able to do such a vital operation in my opinion. Don't you agree?

Regards,
Yenthe

**Comment by ruifranco** [comment]
Truth is I have a db in wich I had to make a copy of the admin user and it wouldn't work because of the missing rule.
But, answering your question, no, I don't agree. It's common for top users (like managers), to want to be able to do backups (and restores), as they like trying Odoo features (and they have the superadmin password - they just don't want to go through the trouble of dealing with Odoo admin). 

;)

**Comment by Yenthe666** [comment]
Hi @ruifranco,

I believe you mean something like this branch? https://github.com/Yenthe666/auto_backup/tree/9.0-security-configuration
Commit: https://github.com/Yenthe666/auto_backup/commit/008d7e673567d0c07fa63aa92b799faab0c9d3ea

User view:
![image](https://user-images.githubusercontent.com/6352350/29711223-1da619ee-8994-11e7-971e-d47fc846edd5.png)

It will add a security rule by default for the administrator user (as this might fix issue https://github.com/Yenthe666/auto_backup/issues/65) and gives the ability to configure access per user.

Regards,
Yenthe

**Comment by ruifranco** [comment]
Yes

**Comment by Yenthe666** [comment]
Hi @ruifranco,

I've handled this in the 11.0 version at commit https://github.com/Yenthe666/auto_backup/commit/96aedf9402a0b8be936d8b0c2a3e5bf3ef4b4ab7
This shouldn't be a problem from 11.0 anymore.
I'd rather not add this in older versions for compatibility and update issues. You can however pick out the things you need if you'd like this. 😉

**Comment by bunja100** [comment]
Hey, i am getting an error when try to install the auto-backup module. it shows db.backup doesn't exist
