### ISSUE TITLE
How to restore it?

### ISSUE THREAD

**Issue by elfeffe** [Yenthe666/auto_backup#63]
I'm trying to restore the backup.
I'm trying to upload it, tried as restore, tried as copy of existing database.
Doesn't work.

I can't find how to restore it.

I need to restore a database with a different name, but I have tried both with correct name and the different one. 
I'm using Odoo 8 (installed 10 days ago)

**Comment by Yenthe666** [comment]
Hi @elfeffe,

What error message are you getting?

Regards,
Yenthe

**Comment by elfeffe** [comment]
I'm trying to restore it with the GUI at /web/database/manager#action=database_manager
I tried with different database name, same, restore, restore as copy.
I even tried ranaming it to .zip
The message is in spanish, but the translation is "Can't restore database". And the logs are empty (not empty, but doesn't say anything about this).
The dump file is not empty, it has a sql file, some folders and a manifest.json

**Comment by elfeffe** [comment]
@Yenthe666 Is there any way to restore from command line?

I have my .dump files, but I just don't know how to restore them

**Comment by Yenthe666** [comment]
@elfeffe if you'd ever need more information - you can find a lot at https://upgrade.odoo.com/database/upload about how to take and restore dumps.

**Comment by manaka02** [comment]
@Yenthe666, I restored my database with success by command line (I use docker) but I don't know how to restore all modules using the **manifest.json**.
If you can tell something about it?

**Comment by Yenthe666** [comment]
Hmm, to be honest, I'm absolutely clueless about the `manifest.json` part. I'm afraid I can't help you there, sorry..

**Comment by manaka02** [comment]
OK thanks, When I use the module, I receive a zip file contains (dump file, filestore and manifest.json). Is this normal?
