### ISSUE TITLE
Backup module stop working

### ISSUE THREAD

**Issue by safecoms** [Yenthe666/auto_backup#64]
Hi Yen,

Thank you so much for this plugin.
I've been using it a lot.

Recently though on all the installed instance, the backup is not working.
It was working before. and it is working on new installation.
I do not understand why I don't have the access anymore.

If I go to the database/manager url, I can do a manual backup.

If I try to add a new backup configuration. the system tell me that the database name does not exist when it does.

Any idea on what to do or look for will be great.
Back up is very important especially for my production instances. Looking forward for any help on this

in the log I get this error message.

2017-08-02 12:18:51,548 3754 ERROR marco odoo.addons.base.ir.ir_cron: Call of self.env[u'db.backup'].schedule_backup(*()) failed in Job 11
Traceback (most recent call last):
  File "/opt/marcopolo/marcopolo-server/odoo/addons/base/ir/ir_cron.py", line 119, in _callback
    getattr(model, method_name)(*args)
  File "/opt/marcopolo/custom/addons/auto_backup/models/db_backup.py", line 138, in schedule_backup
    db_list = self.get_db_list(rec.host, rec.port)
  File "/opt/marcopolo/custom/addons/auto_backup/models/db_backup.py", line 62, in get_db_list
    db_list = execute(conn, 'list')
  File "/opt/marcopolo/custom/addons/auto_backup/models/db_backup.py", line 48, in execute
    res = getattr(connector,method)(*args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1233, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1591, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1273, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1306, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1482, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 794, in close
    raise Fault(**self._stack[0])
Fault: <Fault AccessDenied: 'Access denied'>

**Comment by Yenthe666** [comment]
Hi @safecoms,

Have you configured any form or redirection or load balancing between this? For example Nginx, Amplify, DNS records, HTTP to HTTPS rewrites, ...?

**Comment by safecoms** [comment]
Hi @Yenthe666 

I did made some on Nginx from http to https for some of them.

Some I did not change anything

some I also put them through cloudflare

I also enable the auto vacuum in the postgres configuration

**Comment by safecoms** [comment]
Hi @Yenthe666 
Any feedback where I can look for?

**Comment by Yenthe666** [comment]
Hmm I'm not sure, very hard to give feedback or issues remote. Start from the basics on an instance that has no Nginx, no redirectors, no dockerized containers etc and start looking from there. Otherwise it'll get complex quite fast. You could try to delete the module and install it again, in order to config it again.

**Comment by safecoms** [comment]
The error message does not give you anything?

I will try to delete the module.

When you say delete you mean to uninstall it from the list of application or removing the code itself from the custom addon folder?

**Comment by safecoms** [comment]
Hi @Yenthe666 

I found the main reason.

I uninstall the app on one of the instance having the issue.
Then I install back the app.

I still had the problem.
When I wanted to create a new backup plan, the system was telling me that there was no such database.

Then I realized that one of the changes I made was to add in the odoo configuration file and set the list-db to False.
I had no idea it would have an impact on your module but it does.

so now I need to go through all my instance and reset that setting to True.

Unless you think this could be a bug you can overcome....

Best reagrds,
Philippe

**Comment by Yenthe666** [comment]
Ahh this makes sense, although I would never came up with this 😆. This isn't something that I can bypass from the code directly since the `list-db` key is called right away. It would require me to do unsecure / unethical stuff (if it would even work).

Regards,
Yenthe

**Comment by safecoms** [comment]
I see,
Thank you @Yenthe666 for the feedback.
at least I know I cannot change this configuration.
And thanks for the feedback
👍

**Comment by Yenthe666** [comment]
You're welcome - best of luck!
