### ISSUE TITLE
Here is what we got instead: Error reading SSH protocol banner

### ISSUE THREAD

**Issue by diranetafen** [Yenthe666/auto_backup#66]
Hi
Went i try to test sftp connection i receive this message : Here is what we got instead:
Error reading SSH protocol banner
Environnement:
-> Odoo 10
-> Python 2.7
-> Pysftp : 0.2.8 (i have downgrade from 0.2.9 to 0.2.8 because i was facing the issue No hostkey? #47)

Thanks i in advance for your help !

![bug2](https://user-images.githubusercontent.com/18481009/29718747-0ceb4ed8-89b4-11e7-9094-4ccc37346edc.PNG)
![bug1](https://user-images.githubusercontent.com/18481009/29718748-0d0074de-89b4-11e7-901a-a7cdd8da31af.PNG)

**Comment by Yenthe666** [comment]
Hi @diranetafen,

Have a look at this: https://stackoverflow.com/questions/25609153/paramiko-error-reading-ssh-protocol-banner might be network congestion or too many requests.
