### ISSUE TITLE
Error 'Error ! No such database exists!' when list_db set to false

### ISSUE THREAD

**Issue by BIZ4Africa** [Yenthe666/auto_backup#67]
Hi,

I'm running multiple databases on my server, with following configuraiton
dbfilter ^%h$"
list_db = False

I noticed when configuring auto_backup it fails with error   'Error ! No such database exists!'.
I had to set "list_db = True".

Hope this helps, in case someone faces same issue.

**Comment by Yenthe666** [comment]
Hi @BIZ4Africa,

Thank you for the report - this is indeed the case.
This is because of the following code at https://github.com/Yenthe666/auto_backup/blob/10.0/auto_backup/models/db_backup.py#L90-L99 which will check the db's and if it exists. If you set `list_db` to `False` Odoo will no longer return `db's` which results in this error.
I'll keep this open so more people can see it - should they ever face it.

Regards,
Yenthe

**Comment by Yenthe666** [comment]
Hi @BIZ4Africa,

I've decided to add this in the readme for better visibility.
V9: https://github.com/Yenthe666/auto_backup/commit/098092aea859a96185295e154428b1bb952d42a0
V10: https://github.com/Yenthe666/auto_backup/commit/bf3d9d0fab29b153ffc08f7cc26a766b5f83f3dc
V11: https://github.com/Yenthe666/auto_backup/commit/2da967e7ac58c25a5505283a7a6ef6de2c2397be

I believe this will help better. Thank you once more!

**Comment by malakavitte** [comment]
Hi Yenthe,

I had configured your application with my odoo 11 installation according to your guidelines.but it generate bellow error.i also set list_db = True. i have 4 different databases on same instance.

Error ! No such database exists!

Error details:
111
Connection refused

**Comment by muhsinalungal** [comment]
Hi @Yenthe666, 
Is there anything workaround that will solve this issue, other than setting list_db: True? because I think it is not a good practice to keep that "manage database" screen open.

thanks in advance

**Comment by Yenthe666** [comment]
@muhsinalungal no not at the moment. The `xmlrpc` call that is used to get db names and handle them only finds them when `list_db` is `True`. If I'd want to change that I'd need to redesign the whole part of the app.

**Comment by muhsinalungal** [comment]
@Yenthe666 ok, thanks for the timely reply. anyway, your efforts and contributions are extremely appreciated.

**Comment by Yenthe666** [comment]
@muhsinalungal you're welcome, sorry I can't provide a clean solution for it (for now). Happy to hear that my contributions are appreciated!

**Comment by maccer28** [comment]
Hey @Yenthe666 is this issue still on-going, I pulled the latest for version 12.0 and still have the issue. I can use the workaround technique, but would be nice to not have to. Cheers for the app.

**Comment by Yenthe666** [comment]
Yes it is at least still present up until V13. https://github.com/Yenthe666/auto_backup/commit/c7d0512a0d0b2d42662831008e7a9316b264f23e could've solve this from V13 on

**Comment by maccer28** [comment]
that was quick, thanks for the reply. The good old workaround technique it is.
