### ISSUE TITLE
No module named service

### ISSUE THREAD

**Issue by manish2409** [Yenthe666/auto_backup#7]
Hey On installing, Its giving me an error:

ImportError: No module named Service.
Can you help?

**Comment by Yenthe666** [comment]
@manish2409 another user has made a report on the Odoo forums about this too. As you can see here:https://www.odoo.com/forum/help-1/question/importerror-no-module-named-service-83155
Could you provide me with a log and more details please?

1) Are you running on Ubuntu or Windows and what version?
2) Are you using Odoo 8?
3) Could you provide more details about the log? There should be more warnings/errors which could tell more!.

**Comment by manish2409** [comment]
Hey I am using Ubuntu 12.04 64 bit

**Comment by Yenthe666** [comment]
Please provide the full log & double check you also have pysftp installed. (sudo pip installed pysftp)

**Comment by Yenthe666** [comment]
Since I have far too little details and no responses for 7 days I'll close this.
Feel free to post more / re-open this issue if you have more details!
