### ISSUE TITLE
Mail send function error

### ISSUE THREAD

**Issue by taherg786** [Yenthe666/auto_backup#70]
https://github.com/Yenthe666/auto_backup/blob/10.0/auto_backup/models/db_backup.py#L249
The variables 'cr' and 'user' are undefined. Please fix.

**Comment by Yenthe666** [comment]
Hi @taherg786,

Thank you for your report - this is indeed a bug (didn't notice it when migrating from 8 -> 9 -> 10).
I'll fix it as soon as I can.

Regards,
Yenthe

**Comment by Yenthe666** [comment]
@taherg786,

Could you quickly test this for me please? I don't have time to fully test at the moment. Original:
`ir_mail_server.send_email(cr, user, msg)`
New:
`ir_mail_server.send_email(self._cr, self._uid, msg)`

**Comment by taherg786** [comment]
Thanks for the fix.
I'm sorry, I don't any available servers (enough time actually) to test the mail function.
The error is fixed BTW, and I guess it should work.

**Comment by Yenthe666** [comment]
@taherg786 thanks a lot for the feedback. So, this fixes the issue?

**Comment by taherg786** [comment]
Very well, yes sir!
Thanks a lot.

**Comment by Yenthe666** [comment]
Fixed in https://github.com/Yenthe666/auto_backup/commit/f0d365cbfa17fa69b34654dcbd308d4bc15bc975
