### ISSUE TITLE
[11.0] "name 'datetime' is not defined" while evaluating

### ISSUE THREAD

**Issue by dntq83** [Yenthe666/auto_backup#74]
extra-addons/auto_backup/models/db_backup.py", line 278, in schedule_backup
    createtime = datetime.datetime.fromtimestamp(timestamp)
NameError: name 'datetime' is not defined

**Comment by Yenthe666** [comment]
Hi @dnt83,

Thank you for your bug report.
The `datetime` import was indeed lost when migrating to V11. It is fixed in https://github.com/Yenthe666/auto_backup/commit/09ae7542cc6fe4b942a8bd78006d46c83b3052e8

Regards,
Yenthe
