### ISSUE TITLE
Odoo Break

### ISSUE THREAD

**Issue by albericyao** [Yenthe666/auto_backup#77]
Hi,
After the installation of auto_backup module, my odoo server (9.0) is immediately gone (i have got blank page). I want to know how can I fix it?

**Comment by Yenthe666** [comment]
Hi @albericyao,

Please check your logfiles.
You're most likely missing a dependency which causes this.

**Comment by albericyao** [comment]
Hi Yenthe666,

Thanks ! I will check and give you a feedback soon.


De : Yenthe V.G [mailto:notifications@github.com]
Envoyé : mercredi 22 novembre 2017 08:17
À : Yenthe666/auto_backup <auto_backup@noreply.github.com>
Cc : albericyao <yaoalberic@outlook.com>; Mention <mention@noreply.github.com>
Objet : Re: [Yenthe666/auto_backup] Odoo Break (#77)


Hi @albericyao<https://github.com/albericyao>,

Please check your logfiles.
You're most likely missing a dependency which causes this.

**Comment by Yenthe666** [comment]
@albericyao any feedback? I'm curious.

**Comment by albericyao** [comment]
Hi,

Sorry for this late feedback! All is fix now thank you for your help!

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by Yenthe666** [comment]
Awesome, thanks for the feedback!
