### ISSUE TITLE
Problem when running external database server

### ISSUE THREAD

**Issue by CasVissers-360ERP** [Yenthe666/auto_backup#78]
Hi Yenthe,

The environment I want to use the module on works with a seperate nginx/odoo/postgres server lay-out. When I try to run a back-up I get a traceback:

> 017-12-05 14:33:58,487 2581 ERROR None odoo.http: Postgres subprocess ('/usr/bin/pg_dump', '--no-owner', '--file=/tmp/tmpubuvh1y8/dump.sql', 'wlf') error 1
> Traceback (most recent call last):
>   File "/odoo/odoo/odoo/http.py", line 115, in dispatch_rpc
>     result = dispatch(method, params)
>   File "/odoo/odoo/odoo/service/db.py", line 445, in dispatch
>     return g[exp_method_name](*params)
>   File "<decorator-gen-6>", line 2, in exp_dump
>   File "/odoo/odoo/odoo/service/db.py", line 40, in if_db_mgt_enabled
>     return method(self, *args, **kwargs)
>   File "/odoo/odoo/odoo/service/db.py", line 176, in exp_dump
>     dump_db(db_name, t, format)
>   File "<decorator-gen-8>", line 2, in dump_db
>   File "/odoo/odoo/odoo/service/db.py", line 40, in if_db_mgt_enabled
>     return method(self, *args, **kwargs)
>   File "/odoo/odoo/odoo/service/db.py", line 216, in dump_db
>     odoo.tools.exec_pg_command(*cmd)
>   File "/odoo/odoo/odoo/tools/misc.py", line 128, in exec_pg_command
>     raise Exception('Postgres subprocess %s error %s' % (args2, rc))
> Exception: Postgres subprocess ('/usr/bin/pg_dump', '--no-owner', '--file=/tmp/tmpubuvh1y8/dump.sql', 'wlf') error 1

Do you know a solution for this?

Thanks.
Cas

**Comment by Yenthe666** [comment]
Hi Cas,

Not out of the box. It looks like the backup module can't take the backup as it does not know/have the user to backup with..

**Comment by CasVissers-360ERP** [comment]
The problem was the postgres client was not installed on the Odoo machine. After installing postgresql-client everything runs smoothly.

Thnx!
