### ISSUE TITLE
V11 version restore doesn't work

### ISSUE THREAD

**Issue by CasVissers-360ERP** [Yenthe666/auto_backup#79]
Hi,

When I try to restore a back-up (tested on multiple machines) the restore seems to go well but when I login I get loads of errors like:
ProgrammingError: relation "ir_attachment_id_seq" does not exist
etc.

Can I restore the dump via the frontend of Odoo or do I have to directly load the database into postgres? 

Cas

**Comment by Yenthe666** [comment]
Hi @CasVissers,

When you take a backup from the zip file type it should work fine out of the box. You should be able to restore it from the frontend of Odoo.

**Comment by CasVissers-360ERP** [comment]
@Yenthe666 
I tested on a local ubuntu/windows and remote server installation for multiple databases but restore doesn't seem to work.

**Comment by CasVissers-360ERP** [comment]
Issue was because of different postgres versions on Odoo & Database server. Postgres 9.5 vs 10

**Comment by Yenthe666** [comment]
Ahh that makes sense. Thanks a lot for the feedback Cas!

**Comment by ertus-odoo** [comment]
I have the same problem, impossible to restore database (zip & filestores) on servers in version 9.6.9 from version 10 in local. What is the best solution ? Downgrade local or upgrade server ?

Thanks

**Comment by mohamedmagdy** [comment]
@ertus-odoo , were you able to solve this!

**Comment by nicobustillos** [comment]
Apparently there is a single statement that causes this when creating sequences, which is the "AS INTEGER" in every "CREATE SEQUENCE" which is not supported in PostgreSQL 9.6. 
To work around this, you need to unzip your backup file, open & edit your _dump.sql_ file and delete every occurrence of "AS INTEGER" from every "CREATE SEQUENCE" statement. Then zip the contents again and try to restore one more time. It should work.

**Comment by jwcaceres** [comment]
Thank you nicobustillos, your alternative solved my problem

**Comment by VittorioGoletti** [comment]
Ohh Man, I was getting Crazy due to this error. Apparently my ubuntu upgraded to postgresql 10, and the error started when uploading database from my local to the odoo.sh

**Comment by dinhnguyenjp** [comment]
> Apparently there is a single statement that causes this when creating sequences, which is the "AS INTEGER" in every "CREATE SEQUENCE" which is not supported in PostgreSQL 9.6.
> To work around this, you need to unzip your backup file, open & edit your _dump.sql_ file and delete every occurrence of "AS INTEGER" from every "CREATE SEQUENCE" statement. Then zip the contents again and try to restore one more time. It should work.

Manythanks, You save my day!
