### ISSUE TITLE
[8.0] "Update Modules list" crashes with auto_backup made available to it

### ISSUE THREAD

**Issue by vrms** [Yenthe666/auto_backup#8]
cloned 8.0 branch

1st thing that looks unfamiliar to me is that there is the git folder auto_backup and inside there is a README and another folder auto_backup (which actually is the Module). At least if I make the 'mother' auto_backup folder available, the Module does not show inside of odoo.

now, when I finally make the 2nd tier auto_backup folder available to my addons_patch the "Update Modules List" command returns and error

XmlHttpRequestError INTERNAL SERVER ERROR

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is a

tested this twice with the same result. With your Module available this error pops up, without auto_backp "Update Mouldes List" works fine. I have no coding skills at all and the error message does not tell me anything. Maybe you can make some heads and tails to it

**Comment by vrms** [comment]
well ... If I just had read the docs
   "This module needs the Python library pysftp, otherwise it cannot be installed and used." 

sudo pip install pysftp   and all works just fine, sorry

**Comment by Yenthe666** [comment]
@vrms you need the module inside the main module. I need this setup for the module to show up on the Odoo addons page, its slightly confusing I know..
I'm glad you figured out you needed the pysftp install by yourself :) By the way, normally you should have gotten a warning in your terminal and in Odoo which showed a message, as you can see here in the code: https://github.com/Yenthe666/auto_backup/blob/8.0/auto_backup/backup_scheduler.py#L33.
Anyways, great you found it yourself, have fun with the module!
