### ISSUE TITLE
new install auto_backup on V10...error

### ISSUE THREAD

**Issue by jaronemo** [Yenthe666/auto_backup#83]
Dears:
![image](https://user-images.githubusercontent.com/8476734/34508672-e4fa3fd0-f07c-11e7-9a2d-43093b81ef63.png)

ubuntu 16.04  install new odoo v10 version ...
install this module error...

pysftp question?

**Comment by Yenthe666** [comment]
Hi @jaronemo,

Please have a look at https://github.com/Yenthe666/auto_backup/issues/65

Regards,
Yenthe
