### ISSUE TITLE
pysftp dependency issue with odoo 11

### ISSUE THREAD

**Issue by malakavitte** [Yenthe666/auto_backup#85]
when i install pysftp using bellow commands, it crash my database. when i login to the system, it generate white blank screen and can't continue the process.

sudo apt install python3-pip
pip3 install -U pip
sudo pip3 install pysftp

**Comment by Yenthe666** [comment]
Hi malakavitte,

Is your Odoo running on Python 3 or 2?

Regards,
Yenthe

**Comment by malakavitte** [comment]
Hi Yenthe666,
It's running on python3 and i fixed that issue using bellow command segment.

sudo apt install python3-pip
pip3 install -U pip
sudo pip3 install pysftp
sudo pip3 uninstall pyOpenSSL 
sudo pip3 install pyOpenSSL 
 
when i uninstall and reinstall pyOpenSSL, it turn back to the working environment.

Thanks for the reply!

**Comment by Yenthe666** [comment]
Hi @malakavitte,

Thanks for the feedback & how you've fixed it.
Sadly those packages seem to fail every once in a while but there is no way for me to handle that 😞 

Regards,
Yenthe
