### ISSUE TITLE
Can't find db.backup model

### ISSUE THREAD

**Issue by rjholst** [Yenthe666/auto_backup#88]
Hello by install he can't find db.backup model? win server 2012
What can I do?

![afbeelding](https://user-images.githubusercontent.com/15146925/36351776-ec17fec8-14ae-11e8-9c9c-81f40474f6ed.png)

**Comment by jpaulin** [comment]
I believe have the same error. Installed the auto_backup module according to installation tutorial.
Then further, 
- made settings in /etc/odoo.conf
  Making sure that:
`list_db = True`
- configured the backup in Odoo's Settings menu, as admin

So in my case there's a local folder on the server

/odoo/backups

Linux user 'odoo' owns this, it is the same as the server daemon user. The folder has appropriate read, write, and x ('x' in Linux, for a folder, is right for  jumping into the folder, ie. 'cd' into it)

I've restarted Odoo daemon after changing settings.

What happens in the UI when I manually trigger backup, is a small flash, no errors. A backup doesn't get created.

**Comment by rjholst** [comment]
Thanks voor you commented. But i can't get this module installed because he can't find module he need (db.backup) So before a can config it I need to install it. list_db =true in my config and pysftp is installed.
some other suggestions are welkom.

**Comment by Yenthe666** [comment]
Hi all,

See https://github.com/Yenthe666/auto_backup/issues/65 and check your logfiles. I've seen this one happen on Windows before. A very similar bug report can be found at https://github.com/Yenthe666/auto_backup/issues/110 where I've provided an answer. Basically it is a problem on Windows with the P2 package, I can't do much about that.

**Comment by Tahirhan** [comment]
faced with same issue while starting odoo with ptvsd for debugging purpose. Solved by starting odoo without debugger. and Thanks for module @Yenthe666
