### ISSUE TITLE
no actual backup created

### ISSUE THREAD

**Issue by Quadrill** [Yenthe666/auto_backup#89]
Hi,

I've done all the settings and the test button says that sftp connection is succesfull yet no actual backups are created. It's the same thing for local backups, even when I trigger the Backup scheduler with 'run manually'.
Do you have any advise on what to check?
Thanks for your help.

note: the database name that I  blacked out corresponds to the actual database name in odoo.

![screenshot at feb 20](https://user-images.githubusercontent.com/36652008/36404829-786ff49a-15ed-11e8-9d74-b99d62f494e6.png)

![screenshot at feb 20 schedule](https://user-images.githubusercontent.com/36652008/36404932-fea78a6e-15ed-11e8-90cc-8c2cbd6cec61.png)

**Comment by Yenthe666** [comment]
Hi @Quadrill,

Does the user have enough rights on the remote SFTP folder? Does the SFTP folder exist?
Have a look in the logfiles to see what it says.

**Comment by Quadrill** [comment]
Hi @Yenthe666 ,

thank for your quick reply.
Yes the folder exists and I'm using the admin account which has full rights.
![screenshot at feb 20 09-31-25](https://user-images.githubusercontent.com/36652008/36414106-67d3a86e-1621-11e8-9a49-e01bb98c447f.png)
The issue is that the local backup does not get created either.
![screenshot at feb 20 09-38-48](https://user-images.githubusercontent.com/36652008/36414277-07bff666-1622-11e8-80c0-cd721c1e0834.png)

Does this module have its own log file and where is it located?

**Comment by Yenthe666** [comment]
@Quadrill no, the log statements go into the Odoo log itself.
On a sidenote: your remote system is another OS then Linux, no? I don't think that will work.

**Comment by Quadrill** [comment]
@Yenthe666 
No, the remote system is a Synology (Linux) server.

**Comment by Yenthe666** [comment]
Hmm, then check the Odoo logfile for output 😉

**Comment by Quadrill** [comment]
for the local backup there seems to be a permission issue. for the sftp I haven't figured it out yet.

![screenshot at feb 20 09-50-02](https://user-images.githubusercontent.com/36652008/36414828-f65bee78-1623-11e8-8eac-a4a53ae59e28.png)

**Comment by Yenthe666** [comment]
@Quadrill the SFTP backups are made from the local backups (written away remote) so if it doesn't work locally your SSH won't do anything for the SFTP.

**Comment by Quadrill** [comment]
confirmed. Local backups works now. (did chmod 775 and a chown on the folder). still the sftp to solve.

**Comment by Quadrill** [comment]
@Yenthe666 
Indeed. After fixing the permissions on the local folder, the remote backup is made.
Thanks for the support. All good now. :-)

**Comment by Yenthe666** [comment]
You're welcome and happy to hear it works fine!
