### ISSUE TITLE
Python versions 3.4 vs 3.5

### ISSUE THREAD

**Issue by oussoumab** [Yenthe666/auto_backup#94]
Hi,
I'm using odoo 11.
The module work perfectly with python 3.4 but not working with python 3.5
I even try to log some messages in the "schedule_backup" method but nothing in the log file.
thank you for helping.

**Comment by Yenthe666** [comment]
Hi,

I have tested this module on Python 3.5 and it works fine out of the box.
I'm assuming you have another issue in your Odoo. Please look in the logfiles.
