### ISSUE TITLE
auto_backup module breaks Odoo 11 Enterprise if pasted in addons folder.

### ISSUE THREAD

**Issue by AlexGagea** [Yenthe666/auto_backup#96]
Hello,

I've downloaded the auto_module addon, pasted it into the v11 addons folder, and rebooted the linux server without any installation or modules updated.
After restart, Odoo does not want to load, or the resources i guess.
Any ideas on how to fix this ?

Im working on Odoo 11 Enterprise, Ubuntu 16.04

Thank you.
[odoo-server.log](https://github.com/Yenthe666/auto_backup/files/1824919/odoo-server.log)

**Comment by Yenthe666** [comment]
Did you install the Python dependencies?

**Comment by AlexGagea** [comment]
If you are referring to pysftp, yes i did, with 

sudo pip install pysftp

and

sudo pip3 install pysftp

**Comment by Yenthe666** [comment]
@AlexGagea your log output shows no issues though.
What happens when you add `?debug=assets` in the URL, does it load then? Is there more log output by the way?

**Comment by AlexGagea** [comment]
I've added ?debug=assets in the url, still doesnt work, from chrome console i get the bellow errors : 

ncaught Error: QWeb2: Template 'ActionManager' not found
    at Object.exception (web.assets_common.js:3689)
    at Engine._render (web.assets_common.js:3734)
    at Engine.render (web.assets_common.js:3730)
    at Class.renderElement (web.assets_common.js:3943)
    at web.assets_common.js:3943
    at web.assets_common.js:802
    at fire (web.assets_common.js:796)
    at Object.add [as done] (web.assets_common.js:797)
    at Array.<anonymous> (web.assets_common.js:802)
    at Function.each (web.assets_common.js:625)
web.assets_common.js:3689 Uncaught Error: QWeb2: Template 'CrashManager.error' not found
    at Object.exception (web.assets_common.js:3689)
    at Engine._render (web.assets_common.js:3734)
    at Engine.render (web.assets_common.js:3730)
    at Class.show_error (web.assets_backend.js:585)
    at window.onerror (web.assets_backend.js:503)

Also, another log. ( The exact steps i've made: Copy-pasted the module into addons folder, deleted the log, restarted server, tried to acces odoo from web, retrieved the new log ).
[odoo-server.log](https://github.com/Yenthe666/auto_backup/files/1825078/odoo-server.log)

**Comment by AlexGagea** [comment]
I have to mention that if i remove the module from the addons folder and i restart the server, all returns back to normal.

**Comment by Yenthe666** [comment]
@AlexGagea please run sudo pip3 install paramiko, restart the service and try again.

**Comment by AlexGagea** [comment]
@Yenthe666  , Requirement already satisfied: paramiko in /usr/local/lib/python3.5/dist-package

**Comment by Yenthe666** [comment]
@AlexGagea can you check these two too?
pysftp==0.2.9
pyOpenSSL==16.2.0

Did you restart?

**Comment by AlexGagea** [comment]
pysftp version is 0.2.9, pyOpenSSL was much lower, i've updated it to 17.5.0,  however, still not working.

Also, i've restarted after the python module upgrade

**Comment by Yenthe666** [comment]
Restart of the server too?

**Comment by AlexGagea** [comment]
Yes

**Comment by AlexGagea** [comment]
Forgot to mention something else, the module works fine on Odoo 11 Community, It also worked on Enterprise, i could backup databases. The issue is that, after the first server reboot, it breaks.

**Comment by Yenthe666** [comment]
wait, so now you're saying the module works but breaks after a reboot? Vital info.
on a sidenote, are you on the latest version of the module (downloaded from here as of today)?

**Comment by AlexGagea** [comment]
@Yenthe666  The backup tests were made, 2 months ago, they worked great, yes. I've rebooted the server, and noticed that Odoo doesnt not load the resources. Today, i've downloaded it again from here, pasted into my odoo 11 enterprise addons folder. I did not try to install again, i wanted to see if it still works after the server reboot. Im sorry for failing to mention this.

**Comment by AlexGagea** [comment]
Is there any way so solve this ?

**Comment by Yenthe666** [comment]
Hmm, I'm not sure what is wrong in your environment. I guess you'll have to check the logs of Odoo, pysftp, paramiko and pyOpenSSL. One of those probably has an issue or a broken dependency.

**Comment by AlexGagea** [comment]
After the first time this issue occured, after i spend a day trying to figure this issue out, i had to reset my linux server and re-install odoo. So basically, python and its dependencies were installed again. My odoo installation is from Odoo.com official docs.

**Comment by semmaka** [comment]
I have same issue, I did test on three different fresh & new Community servers & two Enterprise, 

also check all dependencies twice
 
Odoo 11 installation from Odoo.com official docs.

Ubuntu 16.04

Ready to share full access to test environment to get help "if possible will be highly appreciated"

**Comment by Yenthe666** [comment]
@semmaka if you can setup a test environment where it not works I could have a look. Can't guarantee you it is right away or very fast though!

**Comment by semmaka** [comment]
Dear Yenthe,

I drop you an email with my test environment credentials, go please right away or very fast on both ways your support will be highly appreciated.

**Comment by rogerv95** [comment]
I have same issue too, tested several times with new environments on Community version and every time I upload it to the addons folder Odoo breaks. I found same issue trying multiple configurations of the server.
After updating ubuntu, pip, and installing dependencies I came to a different result,  I get a usable odoo but the database selector when login out of it doesn't work. The problem is worst when using firefox. In firefox all icons, and some images don't display and the database selector shows plain text. In safari it works well and I only have issues with some images and the backend community theme backround. When removing the addon from the folder everything gets back to normal.
Also found that when installing another odoo app called "automatic backup to whatever" I get the same problems.
**EDIT TO ADD MORE INFO:**
Every time after reboot the first time loading the page gives 500 Internal error (no matter how long I wait after reboot). Second time loading the page gets to the broken database selector page
<img width="1129" alt="captura de pantalla 2018-03-26 a les 23 25 00" src="https://user-images.githubusercontent.com/28661848/37933908-fb79f942-314c-11e8-97b0-750e542bc558.png">

**Comment by AlexGagea** [comment]
@semmaka Did you manage so find something regarding our issue ?

**Comment by semmaka** [comment]
Nothing yet, just waiting your input.

😀

**Comment by AlexGagea** [comment]
Mine or Yenthe's ? I have no idea what to do or how to solve it.  I tried everything @Yenthe666 Yenthe suggested with no success.

**Comment by semmaka** [comment]
Yenthe's intervention for sure.

**Comment by rogerv95** [comment]
@AlexGagea @semmaka 
Check this issue I opened on Yanthe's install script.  Which installation method did you use?
With the install script mentioned in the issue I've been able to install&use the auto_backup module. I was having the same problem, oddo broken after server or service reboot.
https://github.com/Yenthe666/InstallScript/issues/94

**Comment by jiffingomez** [comment]
Hi @Yenthe666,

I'm having the same issue with Odoo v9 and v10. I have installed pysftp with pip. When I change to developer mode itself odoo breaks. If I remove the module from addons directory, then everything works fine.

**Comment by GillPotter** [comment]
Hi @Yenthe666

I experienced similar issues to those reported above installing Database auto-backup v11.0.1.0 for Odoo v11 Community on a new build of Ubuntu 16.04.4 using Yenthe’s install script.

Database auto-backup appears to need the **Python 3** version of pysftp and I noticed that when running “sudo pip3 install pysftp” I was getting a compilation error because of a missing ssl library.

I installed libssl-dev by running “sudo apt-get install libssl-dev” and then installed pysftp by running “sudo pip3 install pysftp” and it installed cleanly.

Installed Database auto-backup  on Odoo v11 as usual and all issues resolved. Perhaps this might work for other people too.

**Comment by AlexGagea** [comment]
@GillPotter  ,I tried what you did, and still not working.. dont know what else to try..

**Comment by rogerv95** [comment]
@AlexGagea Post your log file and let's see what's happening. It must be a dependency error for sure, is what I was getting all the time and I've been able to solve it and replicate it in multiple test environments I've set up.

**Comment by Yenthe666** [comment]
@AlexGagea check the logfiles. Usually one of those dependencies is failing. Have you installed paramiko too?

**Comment by AlexGagea** [comment]
[odoo-server.log](https://github.com/Yenthe666/auto_backup/files/1951557/odoo-server.log)

So this is what i did to get this log.
1. cleared all odoo  logs.
2. pasted auto_backup module into community v11 addons folder.
3. rebooted linux server
4. started enterprise 11 service.
5. logged with success into community v11.
6. tried to log into enterprise v11 with no success.
Error from Chrome console : 

Uncaught Error: QWeb2: Template 'ActionManager' not found
    at Object.exception (web.assets_common.js:3689)
    at Engine._render (web.assets_common.js:3734)
    at Engine.render (web.assets_common.js:3730)
    at Class.renderElement (web.assets_common.js:3943)
    at web.assets_common.js:3943
    at web.assets_common.js:802
    at fire (web.assets_common.js:796)
    at Object.add [as done] (web.assets_common.js:797)
    at Array.<anonymous> (web.assets_common.js:802)
    at Function.each (web.assets_common.js:625)
web.assets_common.js:3689 Uncaught Error: QWeb2: Template 'CrashManager.error' not found
    at Object.exception (web.assets_common.js:3689)
    at Engine._render (web.assets_common.js:3734)
    at Engine.render (web.assets_common.js:3730)
    at Class.show_error (web.assets_backend.js:585)
    at window.onerror (web.assets_backend.js:503)


...

**Comment by AlexGagea** [comment]
![paramiko](https://user-images.githubusercontent.com/37541211/39311652-350e200c-4976-11e8-8950-56441f92a894.JPG)

And if you say i must install paramiko, check the above photo.

**Comment by Yenthe666** [comment]
@AlexGagea in your logs:
`ImportError: No module named 'asn1crypto'`
I guess one of the child dependencies failed for paramiko / pysftp.

**Comment by AlexGagea** [comment]
if i try to install asn1crypto, its says " requirement already satisfied" ..

**Comment by AlexGagea** [comment]
File "/usr/lib/python3/dist-packages/odoo/addons/auto_backup/models/db_backup.py", line 27, in <module>
    'This module needs paramiko to automatically write backups to the FTP through SFTP. Please install paramiko on your system. (sudo pip3 install paramiko)')
ImportError: This module needs paramiko to automatically write backups to the FTP through SFTP. Please install paramiko on your system. (sudo pip3 install paramiko)


The above is an error from odoo-server log, however, my paramiko is installed in : 
/usr/local/lib/   not usr/lib...   Could this be the issue ? and if so, what to do ?

**Comment by Yenthe666** [comment]
Did your Odoo service and your Linux had a reboot yet? Sometimes Odoo (or the system) cannot find the package without a reboot.

**Comment by AlexGagea** [comment]
Yes, it had. Thats the main issue actually. If i add the auto_backup into odoo addons folder and reboot linux, odoo crashes. Doesnt load anymore




Get Outlook for Android







On Sat, May 26, 2018 at 1:05 PM +0300, "Yenthe V.G" <notifications@github.com> wrote:












Did your Odoo service and your Linux had a reboot yet? Sometimes Odoo (or the system) cannot find the package without a reboot.

**Comment by Yenthe666** [comment]
There has to be a dependency or sub dependency that didn't install correctly and is messing this up. Go through the Odoo log, the paramiko log, the pysftp log and all sub module logs.

**Comment by AlexGagea** [comment]
update : The issue is with paramiko , i have it installed on my linux server, however odoo expects it from a different location than the one i have it installed in. 
To solve the issue, I removed the "import paramiko" line from db_backup.py.
And im transfering the backups to an S3 bucket with s3cmd and a cron job.

**Comment by Yenthe666** [comment]
Hmm odd, it should work. I've got it deployed on dozens of environments. Thanks for the feedback!
