### ISSUE TITLE
Odoo Crashes

### ISSUE THREAD

**Issue by jiffingomez** [Yenthe666/auto_backup#97]
Hi @Yenthe666, 

Downloaded the auto backup from GitHub for Odoo version 9, I'm using windows and Installed pysftp via pip, When I copy the module to addons folder and enable the developer's mode, Odoo crashes. If I remove the module from add-ons, everything works fine.

The same issue is for the auto backup module (Odoo 10)

Let me know if you guys have fixed this issue.

**Comment by Yenthe666** [comment]
Hi @jiffingomez,

Thanks for the bug report.
I've actually had a few people report this but untill now I was not able to reproduce it, the module should work perfect on a Linux atleast. Windows should work as more users have it running but it is not really an environment that I actively check or work on. Long story short: check the logs and if pysftp is succesfully working on your OS.

**Comment by jiffingomez** [comment]
Hi @Yenthe666,

Thanks for your reply, I'm runinng multiple odoo version, previously I had python2.7 when I install pysftp it gets installed in this path. The problem is I have odoo 11 which has python 3.6, I think all other odoo refers this python now. I don't know how to change this. Whenever I install pysftp it gets installed in python2.7 rather in python 3.6.

**Comment by Yenthe666** [comment]
@jiffingomez if you need it for Python 3 you use `pip3`, if you want it for Python 2 you do `pip`
